package org.adempiere.model;

import java.math.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="a_asset_group_acct")
public class AAssetGroupAcct extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aAccumdepreciationAcct;
	private Integer aAssetAcct;
	private Integer aAssetGroupAcctID;
	private Integer aAssetGroupID;
	private String aAssetSpreadType;
	private Integer aDClientID;
	private Integer aDOrgID;
	private Integer aDepreciationAcct;
	private String aDepreciationCalcType;
	private Integer aDepreciationID;
	private BigDecimal aDepreciationManualAmount;
	private String aDepreciationManualPeriod;
	private Integer aDepreciationTableHeaderID;
	private BigDecimal aDepreciationVariablePerc;
	private String aDisposalGain;
	private String aDisposalLoss;
	private String aDisposalRevenue;
	private String aRevalAccumdepOffsetCur;
	private String aRevalAccumdepOffsetPrior;
	private String aRevalCalMethod;
	private String aRevalCostOffset;
	private String aRevalCostOffsetPrior;
	private String aRevalDepexpOffset;
	private BigDecimal aSplitPercent;
	private Boolean active;
	private Integer cAcctSchemaID;
	private String conventionType;
	private String created;
	private Integer createdBy;
	private String depreciationType;
	private String postingType;
	private Boolean processing;
	private String updated;
	private Integer updatedBy;
	private Integer useLifeMonths;
	private Integer useLifeYears;

	public AAssetGroupAcct() {
	}

	public AAssetGroupAcct(Integer aAssetGroupAcctID) {
		this.aAssetGroupAcctID = aAssetGroupAcctID;
	}

	@Basic
	@Column(name="A_ACCUMDEPRECIATION_ACCT", columnDefinition="INT")
	public Integer getAAccumdepreciationAcct() {
		return aAccumdepreciationAcct;
	}

	public void setAAccumdepreciationAcct(Integer aAccumdepreciationAcct) {
		this.aAccumdepreciationAcct = aAccumdepreciationAcct;
	}

	@Basic
	@Column(name="A_ASSET_ACCT", columnDefinition="INT")
	public Integer getAAssetAcct() {
		return aAssetAcct;
	}

	public void setAAssetAcct(Integer aAssetAcct) {
		this.aAssetAcct = aAssetAcct;
	}

	@Id
	@Column(name="A_ASSET_GROUP_ACCT_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_53150", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "A_Asset_Group_Acct", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_53150")
	public Integer getAAssetGroupAcctID() {
		return aAssetGroupAcctID;
	}

	public void setAAssetGroupAcctID(Integer aAssetGroupAcctID) {
		this.aAssetGroupAcctID = aAssetGroupAcctID;
	}

	@Basic
	@Column(name="A_ASSET_GROUP_ID", columnDefinition="INT", nullable=false)
	public Integer getAAssetGroupID() {
		return aAssetGroupID;
	}

	public void setAAssetGroupID(Integer aAssetGroupID) {
		this.aAssetGroupID = aAssetGroupID;
	}

	@Basic
	@Column(name="A_ASSET_SPREAD_TYPE", length=10)
	public String getAAssetSpreadType() {
		return aAssetSpreadType;
	}

	public void setAAssetSpreadType(String aAssetSpreadType) {
		this.aAssetSpreadType = aAssetSpreadType;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Basic
	@Column(name="A_DEPRECIATION_ACCT", columnDefinition="INT")
	public Integer getADepreciationAcct() {
		return aDepreciationAcct;
	}

	public void setADepreciationAcct(Integer aDepreciationAcct) {
		this.aDepreciationAcct = aDepreciationAcct;
	}

	@Basic
	@Column(name="A_DEPRECIATION_CALC_TYPE", nullable=false, length=10)
	public String getADepreciationCalcType() {
		return aDepreciationCalcType;
	}

	public void setADepreciationCalcType(String aDepreciationCalcType) {
		this.aDepreciationCalcType = aDepreciationCalcType;
	}

	@Basic
	@Column(name="A_DEPRECIATION_ID", columnDefinition="INT")
	public Integer getADepreciationID() {
		return aDepreciationID;
	}

	public void setADepreciationID(Integer aDepreciationID) {
		this.aDepreciationID = aDepreciationID;
	}

	@Basic
	@Column(name="A_DEPRECIATION_MANUAL_AMOUNT")
	public BigDecimal getADepreciationManualAmount() {
		return aDepreciationManualAmount;
	}

	public void setADepreciationManualAmount(BigDecimal aDepreciationManualAmount) {
		this.aDepreciationManualAmount = aDepreciationManualAmount;
	}

	@Basic
	@Column(name="A_DEPRECIATION_MANUAL_PERIOD", length=2)
	public String getADepreciationManualPeriod() {
		return aDepreciationManualPeriod;
	}

	public void setADepreciationManualPeriod(String aDepreciationManualPeriod) {
		this.aDepreciationManualPeriod = aDepreciationManualPeriod;
	}

	@Basic
	@Column(name="A_DEPRECIATION_TABLE_HEADER_ID", columnDefinition="INT")
	public Integer getADepreciationTableHeaderID() {
		return aDepreciationTableHeaderID;
	}

	public void setADepreciationTableHeaderID(Integer aDepreciationTableHeaderID) {
		this.aDepreciationTableHeaderID = aDepreciationTableHeaderID;
	}

	@Basic
	@Column(name="A_DEPRECIATION_VARIABLE_PERC")
	public BigDecimal getADepreciationVariablePerc() {
		return aDepreciationVariablePerc;
	}

	public void setADepreciationVariablePerc(BigDecimal aDepreciationVariablePerc) {
		this.aDepreciationVariablePerc = aDepreciationVariablePerc;
	}

	@Basic
	@Column(name="A_DISPOSAL_GAIN", length=10)
	public String getADisposalGain() {
		return aDisposalGain;
	}

	public void setADisposalGain(String aDisposalGain) {
		this.aDisposalGain = aDisposalGain;
	}

	@Basic
	@Column(name="A_DISPOSAL_LOSS", length=22)
	public String getADisposalLoss() {
		return aDisposalLoss;
	}

	public void setADisposalLoss(String aDisposalLoss) {
		this.aDisposalLoss = aDisposalLoss;
	}

	@Basic
	@Column(name="A_DISPOSAL_REVENUE", length=22)
	public String getADisposalRevenue() {
		return aDisposalRevenue;
	}

	public void setADisposalRevenue(String aDisposalRevenue) {
		this.aDisposalRevenue = aDisposalRevenue;
	}

	@Basic
	@Column(name="A_REVAL_ACCUMDEP_OFFSET_CUR", length=22)
	public String getARevalAccumdepOffsetCur() {
		return aRevalAccumdepOffsetCur;
	}

	public void setARevalAccumdepOffsetCur(String aRevalAccumdepOffsetCur) {
		this.aRevalAccumdepOffsetCur = aRevalAccumdepOffsetCur;
	}

	@Basic
	@Column(name="A_REVAL_ACCUMDEP_OFFSET_PRIOR", length=22)
	public String getARevalAccumdepOffsetPrior() {
		return aRevalAccumdepOffsetPrior;
	}

	public void setARevalAccumdepOffsetPrior(String aRevalAccumdepOffsetPrior) {
		this.aRevalAccumdepOffsetPrior = aRevalAccumdepOffsetPrior;
	}

	@Basic
	@Column(name="A_REVAL_CAL_METHOD", length=22)
	public String getARevalCalMethod() {
		return aRevalCalMethod;
	}

	public void setARevalCalMethod(String aRevalCalMethod) {
		this.aRevalCalMethod = aRevalCalMethod;
	}

	@Basic
	@Column(name="A_REVAL_COST_OFFSET", length=22)
	public String getARevalCostOffset() {
		return aRevalCostOffset;
	}

	public void setARevalCostOffset(String aRevalCostOffset) {
		this.aRevalCostOffset = aRevalCostOffset;
	}

	@Basic
	@Column(name="A_REVAL_COST_OFFSET_PRIOR", length=22)
	public String getARevalCostOffsetPrior() {
		return aRevalCostOffsetPrior;
	}

	public void setARevalCostOffsetPrior(String aRevalCostOffsetPrior) {
		this.aRevalCostOffsetPrior = aRevalCostOffsetPrior;
	}

	@Basic
	@Column(name="A_REVAL_DEPEXP_OFFSET", length=22)
	public String getARevalDepexpOffset() {
		return aRevalDepexpOffset;
	}

	public void setARevalDepexpOffset(String aRevalDepexpOffset) {
		this.aRevalDepexpOffset = aRevalDepexpOffset;
	}

	@Basic
	@Column(name="A_SPLIT_PERCENT", nullable=false)
	public BigDecimal getASplitPercent() {
		return aSplitPercent;
	}

	public void setASplitPercent(BigDecimal aSplitPercent) {
		this.aSplitPercent = aSplitPercent;
	}

	@Basic
	@Column(name="ISACTIVE")
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(name="C_ACCTSCHEMA_ID", columnDefinition="INT", nullable=false)
	public Integer getCAcctSchemaID() {
		return cAcctSchemaID;
	}

	public void setCAcctSchemaID(Integer cAcctSchemaID) {
		this.cAcctSchemaID = cAcctSchemaID;
	}

	@Basic
	@Column(nullable=false, length=10)
	public String getConventionType() {
		return conventionType;
	}

	public void setConventionType(String conventionType) {
		this.conventionType = conventionType;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	@Column(nullable=false, length=10)
	public String getDepreciationType() {
		return depreciationType;
	}

	public void setDepreciationType(String depreciationType) {
		this.depreciationType = depreciationType;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getPostingType() {
		return postingType;
	}

	public void setPostingType(String postingType) {
		this.postingType = postingType;
	}

	@Basic
	public Boolean isProcessing() {
		return processing;
	}

	public void setProcessing(Boolean processing) {
		this.processing = processing;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getUseLifeMonths() {
		return useLifeMonths;
	}

	public void setUseLifeMonths(Integer useLifeMonths) {
		this.useLifeMonths = useLifeMonths;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getUseLifeYears() {
		return useLifeYears;
	}

	public void setUseLifeYears(Integer useLifeYears) {
		this.useLifeYears = useLifeYears;
	}
}