package org.adempiere.model;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: org.adempiere.model.ADAlertProcessorLog
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class ADAlertProcessorLogPK implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("org.adempiere.model.ADAlertProcessorLog"); }
		catch(Exception e) {}
	}

	public Integer aDAlertProcessorID;
	public Integer aDAlertProcessorLogID;

	public ADAlertProcessorLogPK() {
	}

	public ADAlertProcessorLogPK(String str) {
		fromString(str);
	}

	public Integer getADAlertProcessorID() {
		return aDAlertProcessorID;
	}

	public void setADAlertProcessorID(Integer aDAlertProcessorID) {
		this.aDAlertProcessorID = aDAlertProcessorID;
	}

	public Integer getADAlertProcessorLogID() {
		return aDAlertProcessorLogID;
	}

	public void setADAlertProcessorLogID(Integer aDAlertProcessorLogID) {
		this.aDAlertProcessorLogID = aDAlertProcessorLogID;
	}

	public String toString() {
		return String.valueOf(aDAlertProcessorID)
			+ "::" + String.valueOf(aDAlertProcessorLogID);
	}

	public int hashCode() {
		int rs = 17;
		rs = rs * 37 + ((aDAlertProcessorID == null) ? 0 : aDAlertProcessorID.hashCode());
		rs = rs * 37 + ((aDAlertProcessorLogID == null) ? 0 : aDAlertProcessorLogID.hashCode());
		return rs;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		ADAlertProcessorLogPK other = (ADAlertProcessorLogPK) obj;
		return ((aDAlertProcessorID == null && other.aDAlertProcessorID == null)
			|| (aDAlertProcessorID != null && aDAlertProcessorID.equals(other.aDAlertProcessorID)))
			&& ((aDAlertProcessorLogID == null && other.aDAlertProcessorLogID == null)
			|| (aDAlertProcessorLogID != null && aDAlertProcessorLogID.equals(other.aDAlertProcessorLogID)));
	}

	private void fromString(String str) {
		Tokenizer toke = new Tokenizer(str);
		str = toke.nextToken();
		if("null".equals(str))
			aDAlertProcessorID = null;
		else
			aDAlertProcessorID = new Integer(str);
		str = toke.nextToken();
		if("null".equals(str))
			aDAlertProcessorLogID = null;
		else
			aDAlertProcessorLogID = new Integer(str);
	}

	protected static class Tokenizer {
		private final String str;
		private int last;

		public Tokenizer (String str) {
			this.str = str;
		}

		public String nextToken () {
			int next = str.indexOf("::", last);
			String part;
			if(next == -1) {
				part = str.substring(last);
				last = str.length();
			} else {
				part = str.substring(last, next);
				last = next + 2;
			}
			return part;
		}
	}
}