package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="ad_client")
public class ADClient extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private String aDLanguage;
	private Integer aDOrgID;
	private Integer aDReplicationStrategyID;
	private Boolean active;
	private String autoArchive;
	private Boolean costImmediate;
	private String created;
	private Integer createdBy;
	private String description;
	private String documentDir;
	private Boolean eMailTest;
	private String ldapquery;
	private String mMPolicy;
	private String modelValidationClasses;
	private Boolean multiLingualDocument;
	private String name;
	private Boolean postImmediate;
	private String requestEMail;
	private String requestFolder;
	private String requestUser;
	private String requestUserPW;
	private String sMTPHost;
	private Boolean serverEMail;
	private Boolean smtpAuthorization;
	private Boolean storeArchiveOnFileSystem;
	private Boolean storeAttachmentsOnFileSystem;
	private String unixArchivePath;
	private String unixAttachmentPath;
	private String updated;
	private Integer updatedBy;
	private Boolean useASP;
	private Boolean useBetaFunctions;
	private String value;
	private String windowsArchivePath;
	private String windowsAttachmentPath;

	public ADClient() {
	}

	public ADClient(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Id
	@Column(name="AD_CLIENT_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_2", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "AD_Client", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_2")
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name="AD_LANGUAGE", length=6)
	public String getADLanguage() {
		return aDLanguage;
	}

	public void setADLanguage(String aDLanguage) {
		this.aDLanguage = aDLanguage;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Basic
	@Column(name="AD_REPLICATIONSTRATEGY_ID", columnDefinition="INT")
	public Integer getADReplicationStrategyID() {
		return aDReplicationStrategyID;
	}

	public void setADReplicationStrategyID(Integer aDReplicationStrategyID) {
		this.aDReplicationStrategyID = aDReplicationStrategyID;
	}

	@Basic
	@Column(name="ISACTIVE", nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getAutoArchive() {
		return autoArchive;
	}

	public void setAutoArchive(String autoArchive) {
		this.autoArchive = autoArchive;
	}

	@Basic
	@Column(name="ISCOSTIMMEDIATE", nullable=false)
	public Boolean isCostImmediate() {
		return costImmediate;
	}

	public void setCostImmediate(Boolean costImmediate) {
		this.costImmediate = costImmediate;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(length=60)
	public String getDocumentDir() {
		return documentDir;
	}

	public void setDocumentDir(String documentDir) {
		this.documentDir = documentDir;
	}

	@Basic
	public Boolean isEMailTest() {
		return eMailTest;
	}

	public void setEMailTest(Boolean eMailTest) {
		this.eMailTest = eMailTest;
	}

	@Basic
	public String getLdapquery() {
		return ldapquery;
	}

	public void setLdapquery(String ldapquery) {
		this.ldapquery = ldapquery;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getMMPolicy() {
		return mMPolicy;
	}

	public void setMMPolicy(String mMPolicy) {
		this.mMPolicy = mMPolicy;
	}

	@Basic
	public String getModelValidationClasses() {
		return modelValidationClasses;
	}

	public void setModelValidationClasses(String modelValidationClasses) {
		this.modelValidationClasses = modelValidationClasses;
	}

	@Basic
	@Column(name="ISMULTILINGUALDOCUMENT", nullable=false)
	public Boolean isMultiLingualDocument() {
		return multiLingualDocument;
	}

	public void setMultiLingualDocument(Boolean multiLingualDocument) {
		this.multiLingualDocument = multiLingualDocument;
	}

	@Basic
	@Column(nullable=false, length=60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	@Column(name="ISPOSTIMMEDIATE", nullable=false)
	public Boolean isPostImmediate() {
		return postImmediate;
	}

	public void setPostImmediate(Boolean postImmediate) {
		this.postImmediate = postImmediate;
	}

	@Basic
	@Column(length=60)
	public String getRequestEMail() {
		return requestEMail;
	}

	public void setRequestEMail(String requestEMail) {
		this.requestEMail = requestEMail;
	}

	@Basic
	@Column(length=20)
	public String getRequestFolder() {
		return requestFolder;
	}

	public void setRequestFolder(String requestFolder) {
		this.requestFolder = requestFolder;
	}

	@Basic
	@Column(length=60)
	public String getRequestUser() {
		return requestUser;
	}

	public void setRequestUser(String requestUser) {
		this.requestUser = requestUser;
	}

	@Basic
	@Column(length=20)
	public String getRequestUserPW() {
		return requestUserPW;
	}

	public void setRequestUserPW(String requestUserPW) {
		this.requestUserPW = requestUserPW;
	}

	@Basic
	@Column(length=60)
	public String getSMTPHost() {
		return sMTPHost;
	}

	public void setSMTPHost(String sMTPHost) {
		this.sMTPHost = sMTPHost;
	}

	@Basic
	@Column(name="ISSERVEREMAIL", nullable=false)
	public Boolean isServerEMail() {
		return serverEMail;
	}

	public void setServerEMail(Boolean serverEMail) {
		this.serverEMail = serverEMail;
	}

	@Basic
	@Column(name="ISSMTPAUTHORIZATION", nullable=false)
	public Boolean isSmtpAuthorization() {
		return smtpAuthorization;
	}

	public void setSmtpAuthorization(Boolean smtpAuthorization) {
		this.smtpAuthorization = smtpAuthorization;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isStoreArchiveOnFileSystem() {
		return storeArchiveOnFileSystem;
	}

	public void setStoreArchiveOnFileSystem(Boolean storeArchiveOnFileSystem) {
		this.storeArchiveOnFileSystem = storeArchiveOnFileSystem;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isStoreAttachmentsOnFileSystem() {
		return storeAttachmentsOnFileSystem;
	}

	public void setStoreAttachmentsOnFileSystem(Boolean storeAttachmentsOnFileSystem) {
		this.storeAttachmentsOnFileSystem = storeAttachmentsOnFileSystem;
	}

	@Basic
	public String getUnixArchivePath() {
		return unixArchivePath;
	}

	public void setUnixArchivePath(String unixArchivePath) {
		this.unixArchivePath = unixArchivePath;
	}

	@Basic
	public String getUnixAttachmentPath() {
		return unixAttachmentPath;
	}

	public void setUnixAttachmentPath(String unixAttachmentPath) {
		this.unixAttachmentPath = unixAttachmentPath;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Basic
	@Column(name="ISUSEASP", nullable=false)
	public Boolean isUseASP() {
		return useASP;
	}

	public void setUseASP(Boolean useASP) {
		this.useASP = useASP;
	}

	@Basic
	@Column(name="ISUSEBETAFUNCTIONS", nullable=false)
	public Boolean isUseBetaFunctions() {
		return useBetaFunctions;
	}

	public void setUseBetaFunctions(Boolean useBetaFunctions) {
		this.useBetaFunctions = useBetaFunctions;
	}

	@Basic
	@Column(nullable=false, length=40)
	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Basic
	public String getWindowsArchivePath() {
		return windowsArchivePath;
	}

	public void setWindowsArchivePath(String windowsArchivePath) {
		this.windowsArchivePath = windowsArchivePath;
	}

	@Basic
	public String getWindowsAttachmentPath() {
		return windowsAttachmentPath;
	}

	public void setWindowsAttachmentPath(String windowsAttachmentPath) {
		this.windowsAttachmentPath = windowsAttachmentPath;
	}
}