package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="ad_clientinfo")
public class AdClientinfo extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer adClientId;
	private Integer adOrgId;
	private Integer adTreeActivityId;
	private Integer adTreeBpartnerId;
	private Integer adTreeCampaignId;
	private Integer adTreeMenuId;
	private Integer adTreeOrgId;
	private Integer adTreeProductId;
	private Integer adTreeProjectId;
	private Integer adTreeSalesregionId;
	private Integer cAcctschema1Id;
	private Integer cBpartnercashtrxId;
	private Integer cCalendarId;
	private Integer cUomLengthId;
	private Integer cUomTimeId;
	private Integer cUomVolumeId;
	private Integer cUomWeightId;
	private String created;
	private Integer createdby;
	private String isactive;
	private String isdiscountlineamt;
	private Integer keeplogdays;
	private Integer logoId;
	private Integer logoreportId;
	private Integer logowebId;
	private Integer mProductfreightId;
	private String updated;
	private Integer updatedby;

	public AdClientinfo() {
	}

	public AdClientinfo(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Id
	@Column(name="AD_CLIENT_ID")
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name="AD_ORG_ID", nullable=false)
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Basic
	@Column(name="AD_TREE_ACTIVITY_ID")
	public Integer getAdTreeActivityId() {
		return adTreeActivityId;
	}

	public void setAdTreeActivityId(Integer adTreeActivityId) {
		this.adTreeActivityId = adTreeActivityId;
	}

	@Basic
	@Column(name="AD_TREE_BPARTNER_ID")
	public Integer getAdTreeBpartnerId() {
		return adTreeBpartnerId;
	}

	public void setAdTreeBpartnerId(Integer adTreeBpartnerId) {
		this.adTreeBpartnerId = adTreeBpartnerId;
	}

	@Basic
	@Column(name="AD_TREE_CAMPAIGN_ID")
	public Integer getAdTreeCampaignId() {
		return adTreeCampaignId;
	}

	public void setAdTreeCampaignId(Integer adTreeCampaignId) {
		this.adTreeCampaignId = adTreeCampaignId;
	}

	@Basic
	@Column(name="AD_TREE_MENU_ID")
	public Integer getAdTreeMenuId() {
		return adTreeMenuId;
	}

	public void setAdTreeMenuId(Integer adTreeMenuId) {
		this.adTreeMenuId = adTreeMenuId;
	}

	@Basic
	@Column(name="AD_TREE_ORG_ID")
	public Integer getAdTreeOrgId() {
		return adTreeOrgId;
	}

	public void setAdTreeOrgId(Integer adTreeOrgId) {
		this.adTreeOrgId = adTreeOrgId;
	}

	@Basic
	@Column(name="AD_TREE_PRODUCT_ID")
	public Integer getAdTreeProductId() {
		return adTreeProductId;
	}

	public void setAdTreeProductId(Integer adTreeProductId) {
		this.adTreeProductId = adTreeProductId;
	}

	@Basic
	@Column(name="AD_TREE_PROJECT_ID")
	public Integer getAdTreeProjectId() {
		return adTreeProjectId;
	}

	public void setAdTreeProjectId(Integer adTreeProjectId) {
		this.adTreeProjectId = adTreeProjectId;
	}

	@Basic
	@Column(name="AD_TREE_SALESREGION_ID")
	public Integer getAdTreeSalesregionId() {
		return adTreeSalesregionId;
	}

	public void setAdTreeSalesregionId(Integer adTreeSalesregionId) {
		this.adTreeSalesregionId = adTreeSalesregionId;
	}

	@Basic
	@Column(name="C_ACCTSCHEMA1_ID")
	public Integer getCAcctschema1Id() {
		return cAcctschema1Id;
	}

	public void setCAcctschema1Id(Integer cAcctschema1Id) {
		this.cAcctschema1Id = cAcctschema1Id;
	}

	@Basic
	@Column(name="C_BPARTNERCASHTRX_ID")
	public Integer getCBpartnercashtrxId() {
		return cBpartnercashtrxId;
	}

	public void setCBpartnercashtrxId(Integer cBpartnercashtrxId) {
		this.cBpartnercashtrxId = cBpartnercashtrxId;
	}

	@Basic
	@Column(name="C_CALENDAR_ID")
	public Integer getCCalendarId() {
		return cCalendarId;
	}

	public void setCCalendarId(Integer cCalendarId) {
		this.cCalendarId = cCalendarId;
	}

	@Basic
	@Column(name="C_UOM_LENGTH_ID")
	public Integer getCUomLengthId() {
		return cUomLengthId;
	}

	public void setCUomLengthId(Integer cUomLengthId) {
		this.cUomLengthId = cUomLengthId;
	}

	@Basic
	@Column(name="C_UOM_TIME_ID")
	public Integer getCUomTimeId() {
		return cUomTimeId;
	}

	public void setCUomTimeId(Integer cUomTimeId) {
		this.cUomTimeId = cUomTimeId;
	}

	@Basic
	@Column(name="C_UOM_VOLUME_ID")
	public Integer getCUomVolumeId() {
		return cUomVolumeId;
	}

	public void setCUomVolumeId(Integer cUomVolumeId) {
		this.cUomVolumeId = cUomVolumeId;
	}

	@Basic
	@Column(name="C_UOM_WEIGHT_ID")
	public Integer getCUomWeightId() {
		return cUomWeightId;
	}

	public void setCUomWeightId(Integer cUomWeightId) {
		this.cUomWeightId = cUomWeightId;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getIsactive() {
		return isactive;
	}

	public void setIsactive(String isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getIsdiscountlineamt() {
		return isdiscountlineamt;
	}

	public void setIsdiscountlineamt(String isdiscountlineamt) {
		this.isdiscountlineamt = isdiscountlineamt;
	}

	@Basic
	public Integer getKeeplogdays() {
		return keeplogdays;
	}

	public void setKeeplogdays(Integer keeplogdays) {
		this.keeplogdays = keeplogdays;
	}

	@Basic
	@Column(name="LOGO_ID")
	public Integer getLogoId() {
		return logoId;
	}

	public void setLogoId(Integer logoId) {
		this.logoId = logoId;
	}

	@Basic
	@Column(name="LOGOREPORT_ID")
	public Integer getLogoreportId() {
		return logoreportId;
	}

	public void setLogoreportId(Integer logoreportId) {
		this.logoreportId = logoreportId;
	}

	@Basic
	@Column(name="LOGOWEB_ID")
	public Integer getLogowebId() {
		return logowebId;
	}

	public void setLogowebId(Integer logowebId) {
		this.logowebId = logowebId;
	}

	@Basic
	@Column(name="M_PRODUCTFREIGHT_ID")
	public Integer getMProductfreightId() {
		return mProductfreightId;
	}

	public void setMProductfreightId(Integer mProductfreightId) {
		this.mProductfreightId = mProductfreightId;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(nullable=false)
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}