package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="a_depreciation_build")
public class ADepreciationBuild extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDepreciationBuildId;
	private Integer aEndAssetId;
	private Integer aStartAssetId;
	private Integer adClientId;
	private Integer adOrgId;
	private Integer cPeriodId;
	private String created;
	private Integer createdby;
	private String dateacct;
	private String datedoc;
	private Boolean isactive;
	private Integer periodno;
	private String postingtype;
	private Boolean processed;
	private Boolean processing;
	private String updated;
	private Integer updatedby;

	public ADepreciationBuild() {
	}

	public ADepreciationBuild(Integer aDepreciationBuildId) {
		this.aDepreciationBuildId = aDepreciationBuildId;
	}

	@Id
	@Column(name="A_DEPRECIATION_BUILD_ID", columnDefinition="INT")
	public Integer getADepreciationBuildId() {
		return aDepreciationBuildId;
	}

	public void setADepreciationBuildId(Integer aDepreciationBuildId) {
		this.aDepreciationBuildId = aDepreciationBuildId;
	}

	@Basic
	@Column(name="A_END_ASSET_ID", columnDefinition="INT")
	public Integer getAEndAssetId() {
		return aEndAssetId;
	}

	public void setAEndAssetId(Integer aEndAssetId) {
		this.aEndAssetId = aEndAssetId;
	}

	@Basic
	@Column(name="A_START_ASSET_ID", columnDefinition="INT")
	public Integer getAStartAssetId() {
		return aStartAssetId;
	}

	public void setAStartAssetId(Integer aStartAssetId) {
		this.aStartAssetId = aStartAssetId;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT")
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT")
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Basic
	@Column(name="C_PERIOD_ID", columnDefinition="INT")
	public Integer getCPeriodId() {
		return cPeriodId;
	}

	public void setCPeriodId(Integer cPeriodId) {
		this.cPeriodId = cPeriodId;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	public String getDateacct() {
		return dateacct;
	}

	public void setDateacct(String dateacct) {
		this.dateacct = dateacct;
	}

	@Basic
	public String getDatedoc() {
		return datedoc;
	}

	public void setDatedoc(String datedoc) {
		this.datedoc = datedoc;
	}

	@Basic
	public Boolean isIsactive() {
		return isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getPeriodno() {
		return periodno;
	}

	public void setPeriodno(Integer periodno) {
		this.periodno = periodno;
	}

	@Basic
	@Column(length=1)
	public String getPostingtype() {
		return postingtype;
	}

	public void setPostingtype(String postingtype) {
		this.postingtype = postingtype;
	}

	@Basic
	public Boolean isProcessed() {
		return processed;
	}

	public void setProcessed(Boolean processed) {
		this.processed = processed;
	}

	@Basic
	public Boolean isProcessing() {
		return processing;
	}

	public void setProcessing(Boolean processing) {
		this.processing = processing;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}