package org.adempiere.model;

import java.math.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="a_depreciation_workfile")
public class ADepreciationWorkfile extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private BigDecimal aAccumulatedDepr;
	private BigDecimal aAssetCost;
	private Integer aAssetId;
	private BigDecimal aAssetLifeCurrentYear;
	private Integer aAssetLifeYears;
	private BigDecimal aBaseAmount;
	private BigDecimal aCalcAccumulatedDepr;
	private BigDecimal aCurrDepExp;
	private Integer aCurrentPeriod;
	private Integer aDepreciationWorkfileId;
	private Integer aLifePeriod;
	private BigDecimal aPeriodForecast;
	private Integer aPeriodPosted;
	private BigDecimal aPriorYearAccumulatedDepr;
	private BigDecimal aQtyCurrent;
	private BigDecimal aSalvageValue;
	private Integer adClientId;
	private Integer adOrgId;
	private String assetdepreciationdate;
	private String created;
	private Integer createdby;
	private String dateacct;
	private Boolean isactive;
	private Boolean isdepreciated;
	private String postingtype;
	private Boolean processing;
	private String updated;
	private Integer updatedby;

	public ADepreciationWorkfile() {
	}

	public ADepreciationWorkfile(Integer aDepreciationWorkfileId) {
		this.aDepreciationWorkfileId = aDepreciationWorkfileId;
	}

	@Basic
	@Column(name="A_ACCUMULATED_DEPR")
	public BigDecimal getAAccumulatedDepr() {
		return aAccumulatedDepr;
	}

	public void setAAccumulatedDepr(BigDecimal aAccumulatedDepr) {
		this.aAccumulatedDepr = aAccumulatedDepr;
	}

	@Basic
	@Column(name="A_ASSET_COST")
	public BigDecimal getAAssetCost() {
		return aAssetCost;
	}

	public void setAAssetCost(BigDecimal aAssetCost) {
		this.aAssetCost = aAssetCost;
	}

	@Basic
	@Column(name="A_ASSET_ID", columnDefinition="INT", nullable=false)
	public Integer getAAssetId() {
		return aAssetId;
	}

	public void setAAssetId(Integer aAssetId) {
		this.aAssetId = aAssetId;
	}

	@Basic
	@Column(name="A_ASSET_LIFE_CURRENT_YEAR")
	public BigDecimal getAAssetLifeCurrentYear() {
		return aAssetLifeCurrentYear;
	}

	public void setAAssetLifeCurrentYear(BigDecimal aAssetLifeCurrentYear) {
		this.aAssetLifeCurrentYear = aAssetLifeCurrentYear;
	}

	@Basic
	@Column(name="A_ASSET_LIFE_YEARS", columnDefinition="INT", nullable=false)
	public Integer getAAssetLifeYears() {
		return aAssetLifeYears;
	}

	public void setAAssetLifeYears(Integer aAssetLifeYears) {
		this.aAssetLifeYears = aAssetLifeYears;
	}

	@Basic
	@Column(name="A_BASE_AMOUNT")
	public BigDecimal getABaseAmount() {
		return aBaseAmount;
	}

	public void setABaseAmount(BigDecimal aBaseAmount) {
		this.aBaseAmount = aBaseAmount;
	}

	@Basic
	@Column(name="A_CALC_ACCUMULATED_DEPR")
	public BigDecimal getACalcAccumulatedDepr() {
		return aCalcAccumulatedDepr;
	}

	public void setACalcAccumulatedDepr(BigDecimal aCalcAccumulatedDepr) {
		this.aCalcAccumulatedDepr = aCalcAccumulatedDepr;
	}

	@Basic
	@Column(name="A_CURR_DEP_EXP")
	public BigDecimal getACurrDepExp() {
		return aCurrDepExp;
	}

	public void setACurrDepExp(BigDecimal aCurrDepExp) {
		this.aCurrDepExp = aCurrDepExp;
	}

	@Basic
	@Column(name="A_CURRENT_PERIOD", columnDefinition="INT")
	public Integer getACurrentPeriod() {
		return aCurrentPeriod;
	}

	public void setACurrentPeriod(Integer aCurrentPeriod) {
		this.aCurrentPeriod = aCurrentPeriod;
	}

	@Id
	@Column(name="A_DEPRECIATION_WORKFILE_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_53136", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "A_Depreciation_Workfile", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_53136")
	public Integer getADepreciationWorkfileId() {
		return aDepreciationWorkfileId;
	}

	public void setADepreciationWorkfileId(Integer aDepreciationWorkfileId) {
		this.aDepreciationWorkfileId = aDepreciationWorkfileId;
	}

	@Basic
	@Column(name="A_LIFE_PERIOD", columnDefinition="INT")
	public Integer getALifePeriod() {
		return aLifePeriod;
	}

	public void setALifePeriod(Integer aLifePeriod) {
		this.aLifePeriod = aLifePeriod;
	}

	@Basic
	@Column(name="A_PERIOD_FORECAST")
	public BigDecimal getAPeriodForecast() {
		return aPeriodForecast;
	}

	public void setAPeriodForecast(BigDecimal aPeriodForecast) {
		this.aPeriodForecast = aPeriodForecast;
	}

	@Basic
	@Column(name="A_PERIOD_POSTED", columnDefinition="INT")
	public Integer getAPeriodPosted() {
		return aPeriodPosted;
	}

	public void setAPeriodPosted(Integer aPeriodPosted) {
		this.aPeriodPosted = aPeriodPosted;
	}

	@Basic
	@Column(name="A_PRIOR_YEAR_ACCUMULATED_DEPR")
	public BigDecimal getAPriorYearAccumulatedDepr() {
		return aPriorYearAccumulatedDepr;
	}

	public void setAPriorYearAccumulatedDepr(BigDecimal aPriorYearAccumulatedDepr) {
		this.aPriorYearAccumulatedDepr = aPriorYearAccumulatedDepr;
	}

	@Basic
	@Column(name="A_QTY_CURRENT", nullable=false)
	public BigDecimal getAQtyCurrent() {
		return aQtyCurrent;
	}

	public void setAQtyCurrent(BigDecimal aQtyCurrent) {
		this.aQtyCurrent = aQtyCurrent;
	}

	@Basic
	@Column(name="A_SALVAGE_VALUE")
	public BigDecimal getASalvageValue() {
		return aSalvageValue;
	}

	public void setASalvageValue(BigDecimal aSalvageValue) {
		this.aSalvageValue = aSalvageValue;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Basic
	public String getAssetdepreciationdate() {
		return assetdepreciationdate;
	}

	public void setAssetdepreciationdate(String assetdepreciationdate) {
		this.assetdepreciationdate = assetdepreciationdate;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	public String getDateacct() {
		return dateacct;
	}

	public void setDateacct(String dateacct) {
		this.dateacct = dateacct;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsactive() {
		return isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	@Basic
	public Boolean isIsdepreciated() {
		return isdepreciated;
	}

	public void setIsdepreciated(Boolean isdepreciated) {
		this.isdepreciated = isdepreciated;
	}

	@Basic
	@Column(length=1)
	public String getPostingtype() {
		return postingtype;
	}

	public void setPostingtype(String postingtype) {
		this.postingtype = postingtype;
	}

	@Basic
	public Boolean isProcessing() {
		return processing;
	}

	public void setProcessing(Boolean processing) {
		this.processing = processing;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}