package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="a_depreciation_table_header")
public class ADepreciationTableHeader extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private String aDepreciationTableCode;
	private Integer aDepreciationTableHeaderId;
	private String aTableRateType;
	private String aTerm;
	private Integer adClientId;
	private Integer adOrgId;
	private String created;
	private Integer createdby;
	private String description;
	private String isactive;
	private String processed;
	private String updated;
	private Integer updatedby;

	public ADepreciationTableHeader() {
	}

	public ADepreciationTableHeader(Integer aDepreciationTableHeaderId) {
		this.aDepreciationTableHeaderId = aDepreciationTableHeaderId;
	}

	@Basic
	@Column(name="A_DEPRECIATION_TABLE_CODE", nullable=false, length=20)
	public String getADepreciationTableCode() {
		return aDepreciationTableCode;
	}

	public void setADepreciationTableCode(String aDepreciationTableCode) {
		this.aDepreciationTableCode = aDepreciationTableCode;
	}

	@Id
	@Column(name="A_DEPRECIATION_TABLE_HEADER_ID")
	public Integer getADepreciationTableHeaderId() {
		return aDepreciationTableHeaderId;
	}

	public void setADepreciationTableHeaderId(Integer aDepreciationTableHeaderId) {
		this.aDepreciationTableHeaderId = aDepreciationTableHeaderId;
	}

	@Basic
	@Column(name="A_TABLE_RATE_TYPE", nullable=false, length=2)
	public String getATableRateType() {
		return aTableRateType;
	}

	public void setATableRateType(String aTableRateType) {
		this.aTableRateType = aTableRateType;
	}

	@Basic
	@Column(name="A_TERM", nullable=false, length=2)
	public String getATerm() {
		return aTerm;
	}

	public void setATerm(String aTerm) {
		this.aTerm = aTerm;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", nullable=false)
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name="AD_ORG_ID", nullable=false)
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(nullable=false, length=510)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getIsactive() {
		return isactive;
	}

	public void setIsactive(String isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getProcessed() {
		return processed;
	}

	public void setProcessed(String processed) {
		this.processed = processed;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(nullable=false)
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}