package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="ad_field")
public class AdField extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer adClientId;
	private Integer adColumnId;
	private Integer adFieldId;
	private Integer adFieldgroupId;
	private Integer adOrgId;
	private Integer adReferenceId;
	private Integer adReferenceValueId;
	private Integer adTabId;
	private Integer adValRuleId;
	private String created;
	private Integer createdby;
	private String defaultvalue;
	private String description;
	private Integer displaylength;
	private String displaylogic;
	private String entitytype;
	private String help;
	private Integer includedTabId;
	private String infofactoryclass;
	private Boolean isactive;
	private Boolean iscentrallymaintained;
	private Boolean isdisplayed;
	private Boolean isencrypted;
	private Boolean isfieldonly;
	private Boolean isheading;
	private Boolean ismandatory;
	private Boolean isreadonly;
	private Boolean issameline;
	private String name;
	private String obscuretype;
	private Integer seqno;
	private Integer sortno;
	private String updated;
	private Integer updatedby;

	public AdField() {
	}

	public AdField(Integer adFieldId) {
		this.adFieldId = adFieldId;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name="AD_COLUMN_ID", columnDefinition="INT")
	public Integer getAdColumnId() {
		return adColumnId;
	}

	public void setAdColumnId(Integer adColumnId) {
		this.adColumnId = adColumnId;
	}

	@Id
	@Column(name="AD_FIELD_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_4", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "AD_Field", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_4")
	public Integer getAdFieldId() {
		return adFieldId;
	}

	public void setAdFieldId(Integer adFieldId) {
		this.adFieldId = adFieldId;
	}

	@Basic
	@Column(name="AD_FIELDGROUP_ID", columnDefinition="INT")
	public Integer getAdFieldgroupId() {
		return adFieldgroupId;
	}

	public void setAdFieldgroupId(Integer adFieldgroupId) {
		this.adFieldgroupId = adFieldgroupId;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Basic
	@Column(name="AD_REFERENCE_ID", columnDefinition="INT")
	public Integer getAdReferenceId() {
		return adReferenceId;
	}

	public void setAdReferenceId(Integer adReferenceId) {
		this.adReferenceId = adReferenceId;
	}

	@Basic
	@Column(name="AD_REFERENCE_VALUE_ID", columnDefinition="INT")
	public Integer getAdReferenceValueId() {
		return adReferenceValueId;
	}

	public void setAdReferenceValueId(Integer adReferenceValueId) {
		this.adReferenceValueId = adReferenceValueId;
	}

	@Basic
	@Column(name="AD_TAB_ID", columnDefinition="INT", nullable=false)
	public Integer getAdTabId() {
		return adTabId;
	}

	public void setAdTabId(Integer adTabId) {
		this.adTabId = adTabId;
	}

	@Basic
	@Column(name="AD_VAL_RULE_ID", columnDefinition="INT")
	public Integer getAdValRuleId() {
		return adValRuleId;
	}

	public void setAdValRuleId(Integer adValRuleId) {
		this.adValRuleId = adValRuleId;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(length=2000)
	public String getDefaultvalue() {
		return defaultvalue;
	}

	public void setDefaultvalue(String defaultvalue) {
		this.defaultvalue = defaultvalue;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getDisplaylength() {
		return displaylength;
	}

	public void setDisplaylength(Integer displaylength) {
		this.displaylength = displaylength;
	}

	@Basic
	@Column(length=2000)
	public String getDisplaylogic() {
		return displaylogic;
	}

	public void setDisplaylogic(String displaylogic) {
		this.displaylogic = displaylogic;
	}

	@Basic
	@Column(nullable=false, length=40)
	public String getEntitytype() {
		return entitytype;
	}

	public void setEntitytype(String entitytype) {
		this.entitytype = entitytype;
	}

	@Basic
	@Column(length=2000)
	public String getHelp() {
		return help;
	}

	public void setHelp(String help) {
		this.help = help;
	}

	@Basic
	@Column(name="INCLUDED_TAB_ID", columnDefinition="INT")
	public Integer getIncludedTabId() {
		return includedTabId;
	}

	public void setIncludedTabId(Integer includedTabId) {
		this.includedTabId = includedTabId;
	}

	@Basic
	public String getInfofactoryclass() {
		return infofactoryclass;
	}

	public void setInfofactoryclass(String infofactoryclass) {
		this.infofactoryclass = infofactoryclass;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsactive() {
		return isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIscentrallymaintained() {
		return iscentrallymaintained;
	}

	public void setIscentrallymaintained(Boolean iscentrallymaintained) {
		this.iscentrallymaintained = iscentrallymaintained;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsdisplayed() {
		return isdisplayed;
	}

	public void setIsdisplayed(Boolean isdisplayed) {
		this.isdisplayed = isdisplayed;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsencrypted() {
		return isencrypted;
	}

	public void setIsencrypted(Boolean isencrypted) {
		this.isencrypted = isencrypted;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsfieldonly() {
		return isfieldonly;
	}

	public void setIsfieldonly(Boolean isfieldonly) {
		this.isfieldonly = isfieldonly;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsheading() {
		return isheading;
	}

	public void setIsheading(Boolean isheading) {
		this.isheading = isheading;
	}

	@Basic
	@Column(length=1)
	public Boolean isIsmandatory() {
		return ismandatory;
	}

	public void setIsmandatory(Boolean ismandatory) {
		this.ismandatory = ismandatory;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsreadonly() {
		return isreadonly;
	}

	public void setIsreadonly(Boolean isreadonly) {
		this.isreadonly = isreadonly;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIssameline() {
		return issameline;
	}

	public void setIssameline(Boolean issameline) {
		this.issameline = issameline;
	}

	@Basic
	@Column(nullable=false, length=60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	@Column(length=3)
	public String getObscuretype() {
		return obscuretype;
	}

	public void setObscuretype(String obscuretype) {
		this.obscuretype = obscuretype;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getSeqno() {
		return seqno;
	}

	public void setSeqno(Integer seqno) {
		this.seqno = seqno;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getSortno() {
		return sortno;
	}

	public void setSortno(Integer sortno) {
		this.sortno = sortno;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}