package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="ad_package_imp_detail")
public class AdPackageImpDetail extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private String action;
	private Integer adBackupId;
	private Integer adClientId;
	private Integer adOrgId;
	private Integer adOriginalId;
	private Integer adPackageImpDetailId;
	private Integer adPackageImpId;
	private Integer adTableId;
	private String created;
	private Integer createdby;
	private String isactive;
	private String name;
	private String success;
	private String tablename;
	private String type;
	private String uninstall;
	private String updated;
	private Integer updatedby;

	public AdPackageImpDetail() {
	}

	public AdPackageImpDetail(Integer adPackageImpDetailId) {
		this.adPackageImpDetailId = adPackageImpDetailId;
	}

	@Basic
	@Column(length=20)
	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Basic
	@Column(name="AD_BACKUP_ID")
	public Integer getAdBackupId() {
		return adBackupId;
	}

	public void setAdBackupId(Integer adBackupId) {
		this.adBackupId = adBackupId;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", nullable=false)
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name="AD_ORG_ID", nullable=false)
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Basic
	@Column(name="AD_ORIGINAL_ID", nullable=false)
	public Integer getAdOriginalId() {
		return adOriginalId;
	}

	public void setAdOriginalId(Integer adOriginalId) {
		this.adOriginalId = adOriginalId;
	}

	@Id
	@Column(name="AD_PACKAGE_IMP_DETAIL_ID")
	public Integer getAdPackageImpDetailId() {
		return adPackageImpDetailId;
	}

	public void setAdPackageImpDetailId(Integer adPackageImpDetailId) {
		this.adPackageImpDetailId = adPackageImpDetailId;
	}

	@Basic
	@Column(name="AD_PACKAGE_IMP_ID", nullable=false)
	public Integer getAdPackageImpId() {
		return adPackageImpId;
	}

	public void setAdPackageImpId(Integer adPackageImpId) {
		this.adPackageImpId = adPackageImpId;
	}

	@Basic
	@Column(name="AD_TABLE_ID")
	public Integer getAdTableId() {
		return adTableId;
	}

	public void setAdTableId(Integer adTableId) {
		this.adTableId = adTableId;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getIsactive() {
		return isactive;
	}

	public void setIsactive(String isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(length=60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	@Column(length=20)
	public String getSuccess() {
		return success;
	}

	public void setSuccess(String success) {
		this.success = success;
	}

	@Basic
	@Column(length=60)
	public String getTablename() {
		return tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	@Basic
	@Column(length=60)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Basic
	@Column(length=1)
	public String getUninstall() {
		return uninstall;
	}

	public void setUninstall(String uninstall) {
		this.uninstall = uninstall;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(nullable=false)
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}