package org.adempiere.model;

import java.math.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="ad_pinstance_para")
@IdClass(org.adempiere.model.AdPinstanceParaPK.class)
public class AdPinstancePara extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer adClientId;
	private Integer adOrgId;
	private Integer adPinstanceId;
	private String created;
	private Integer createdby;
	private String info;
	private String infoTo;
	private Boolean isactive;
	private String pDate;
	private String pDateTo;
	private BigDecimal pNumber;
	private BigDecimal pNumberTo;
	private String pString;
	private String pStringTo;
	private String parametername;
	private Integer seqno;
	private String updated;
	private Integer updatedby;

	public AdPinstancePara() {
	}

	public AdPinstancePara(Integer adPinstanceId, Integer seqno) {
		this.adPinstanceId = adPinstanceId;
		this.seqno = seqno;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT")
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT")
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Id
	@Column(name="AD_PINSTANCE_ID", columnDefinition="INT")
	public Integer getAdPinstanceId() {
		return adPinstanceId;
	}

	public void setAdPinstanceId(Integer adPinstanceId) {
		this.adPinstanceId = adPinstanceId;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(length=60)
	public String getInfo() {
		return info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Basic
	@Column(name="INFO_TO", length=60)
	public String getInfoTo() {
		return infoTo;
	}

	public void setInfoTo(String infoTo) {
		this.infoTo = infoTo;
	}

	@Basic
	public Boolean isIsactive() {
		return isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(name="P_DATE")
	public String getPDate() {
		return pDate;
	}

	public void setPDate(String pDate) {
		this.pDate = pDate;
	}

	@Basic
	@Column(name="P_DATE_TO")
	public String getPDateTo() {
		return pDateTo;
	}

	public void setPDateTo(String pDateTo) {
		this.pDateTo = pDateTo;
	}

	@Basic
	@Column(name="P_NUMBER")
	public BigDecimal getPNumber() {
		return pNumber;
	}

	public void setPNumber(BigDecimal pNumber) {
		this.pNumber = pNumber;
	}

	@Basic
	@Column(name="P_NUMBER_TO")
	public BigDecimal getPNumberTo() {
		return pNumberTo;
	}

	public void setPNumberTo(BigDecimal pNumberTo) {
		this.pNumberTo = pNumberTo;
	}

	@Basic
	@Column(name="P_STRING")
	public String getPString() {
		return pString;
	}

	public void setPString(String pString) {
		this.pString = pString;
	}

	@Basic
	@Column(name="P_STRING_TO")
	public String getPStringTo() {
		return pStringTo;
	}

	public void setPStringTo(String pStringTo) {
		this.pStringTo = pStringTo;
	}

	@Basic
	@Column(length=60)
	public String getParametername() {
		return parametername;
	}

	public void setParametername(String parametername) {
		this.parametername = parametername;
	}

	@Id
	@Column(columnDefinition="INT")
	public Integer getSeqno() {
		return seqno;
	}

	public void setSeqno(Integer seqno) {
		this.seqno = seqno;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}