package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="ad_printgraph")
public class ADPrintGraph extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private Integer aDOrgID;
	private Integer aDPrintFormatID;
	private Integer aDPrintGraphID;
	private Boolean active;
	private String created;
	private Integer createdBy;
	private Integer data1PrintFormatItemID;
	private Integer data2PrintFormatItemID;
	private Integer data3PrintFormatItemID;
	private Integer data4PrintFormatItemID;
	private Integer dataPrintFormatItemID;
	private String description;
	private Integer descriptionPrintFormatItemID;
	private String graphType;
	private String name;
	private String updated;
	private Integer updatedBy;

	public ADPrintGraph() {
	}

	public ADPrintGraph(Integer aDPrintGraphID) {
		this.aDPrintGraphID = aDPrintGraphID;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Basic
	@Column(name="AD_PRINTFORMAT_ID", columnDefinition="INT", nullable=false)
	public Integer getADPrintFormatID() {
		return aDPrintFormatID;
	}

	public void setADPrintFormatID(Integer aDPrintFormatID) {
		this.aDPrintFormatID = aDPrintFormatID;
	}

	@Id
	@Column(name="AD_PRINTGRAPH_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_617", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "AD_PrintGraph", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_617")
	public Integer getADPrintGraphID() {
		return aDPrintGraphID;
	}

	public void setADPrintGraphID(Integer aDPrintGraphID) {
		this.aDPrintGraphID = aDPrintGraphID;
	}

	@Basic
	@Column(name="ISACTIVE", nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	@Column(name="DATA1_PRINTFORMATITEM_ID", columnDefinition="INT")
	public Integer getData1PrintFormatItemID() {
		return data1PrintFormatItemID;
	}

	public void setData1PrintFormatItemID(Integer data1PrintFormatItemID) {
		this.data1PrintFormatItemID = data1PrintFormatItemID;
	}

	@Basic
	@Column(name="DATA2_PRINTFORMATITEM_ID", columnDefinition="INT")
	public Integer getData2PrintFormatItemID() {
		return data2PrintFormatItemID;
	}

	public void setData2PrintFormatItemID(Integer data2PrintFormatItemID) {
		this.data2PrintFormatItemID = data2PrintFormatItemID;
	}

	@Basic
	@Column(name="DATA3_PRINTFORMATITEM_ID", columnDefinition="INT")
	public Integer getData3PrintFormatItemID() {
		return data3PrintFormatItemID;
	}

	public void setData3PrintFormatItemID(Integer data3PrintFormatItemID) {
		this.data3PrintFormatItemID = data3PrintFormatItemID;
	}

	@Basic
	@Column(name="DATA4_PRINTFORMATITEM_ID", columnDefinition="INT")
	public Integer getData4PrintFormatItemID() {
		return data4PrintFormatItemID;
	}

	public void setData4PrintFormatItemID(Integer data4PrintFormatItemID) {
		this.data4PrintFormatItemID = data4PrintFormatItemID;
	}

	@Basic
	@Column(name="DATA_PRINTFORMATITEM_ID", columnDefinition="INT", nullable=false)
	public Integer getDataPrintFormatItemID() {
		return dataPrintFormatItemID;
	}

	public void setDataPrintFormatItemID(Integer dataPrintFormatItemID) {
		this.dataPrintFormatItemID = dataPrintFormatItemID;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(name="DESCRIPTION_PRINTFORMATITEM_ID", columnDefinition="INT", nullable=false)
	public Integer getDescriptionPrintFormatItemID() {
		return descriptionPrintFormatItemID;
	}

	public void setDescriptionPrintFormatItemID(Integer descriptionPrintFormatItemID) {
		this.descriptionPrintFormatItemID = descriptionPrintFormatItemID;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getGraphType() {
		return graphType;
	}

	public void setGraphType(String graphType) {
		this.graphType = graphType;
	}

	@Basic
	@Column(nullable=false, length=60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}
}