package org.adempiere.model;

import java.math.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="ad_printpaper")
public class AdPrintpaper extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer adClientId;
	private Integer adOrgId;
	private Integer adPrintpaperId;
	private String code;
	private String created;
	private Integer createdby;
	private String description;
	private String dimensionunits;
	private Boolean isactive;
	private Boolean isdefault;
	private Boolean islandscape;
	private Integer marginbottom;
	private Integer marginleft;
	private Integer marginright;
	private Integer margintop;
	private String name;
	private Boolean processing;
	private BigDecimal sizex;
	private BigDecimal sizey;
	private String updated;
	private Integer updatedby;

	public AdPrintpaper() {
	}

	public AdPrintpaper(Integer adPrintpaperId) {
		this.adPrintpaperId = adPrintpaperId;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Id
	@Column(name="AD_PRINTPAPER_ID", columnDefinition="INT")
	public Integer getAdPrintpaperId() {
		return adPrintpaperId;
	}

	public void setAdPrintpaperId(Integer adPrintpaperId) {
		this.adPrintpaperId = adPrintpaperId;
	}

	@Basic
	@Column(nullable=false, length=2000)
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(length=1)
	public String getDimensionunits() {
		return dimensionunits;
	}

	public void setDimensionunits(String dimensionunits) {
		this.dimensionunits = dimensionunits;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsactive() {
		return isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsdefault() {
		return isdefault;
	}

	public void setIsdefault(Boolean isdefault) {
		this.isdefault = isdefault;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIslandscape() {
		return islandscape;
	}

	public void setIslandscape(Boolean islandscape) {
		this.islandscape = islandscape;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getMarginbottom() {
		return marginbottom;
	}

	public void setMarginbottom(Integer marginbottom) {
		this.marginbottom = marginbottom;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getMarginleft() {
		return marginleft;
	}

	public void setMarginleft(Integer marginleft) {
		this.marginleft = marginleft;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getMarginright() {
		return marginright;
	}

	public void setMarginright(Integer marginright) {
		this.marginright = marginright;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getMargintop() {
		return margintop;
	}

	public void setMargintop(Integer margintop) {
		this.margintop = margintop;
	}

	@Basic
	@Column(nullable=false, length=60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	public Boolean isProcessing() {
		return processing;
	}

	public void setProcessing(Boolean processing) {
		this.processing = processing;
	}

	@Basic
	public BigDecimal getSizex() {
		return sizex;
	}

	public void setSizex(BigDecimal sizex) {
		this.sizex = sizex;
	}

	@Basic
	public BigDecimal getSizey() {
		return sizey;
	}

	public void setSizey(BigDecimal sizey) {
		this.sizey = sizey;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}