package org.adempiere.model;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: org.adempiere.model.ADProcessParaTrl
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class ADProcessParaTrlPK implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("org.adempiere.model.ADProcessParaTrl"); }
		catch(Exception e) {}
	}

	public Integer aDLanguageID;
	public Integer aDProcessParaID;

	public ADProcessParaTrlPK() {
	}

	public ADProcessParaTrlPK(String str) {
		fromString(str);
	}

	public Integer getADLanguageID() {
		return aDLanguageID;
	}

	public void setADLanguageID(Integer aDLanguageID) {
		this.aDLanguageID = aDLanguageID;
	}

	public Integer getADProcessParaID() {
		return aDProcessParaID;
	}

	public void setADProcessParaID(Integer aDProcessParaID) {
		this.aDProcessParaID = aDProcessParaID;
	}

	public String toString() {
		return aDLanguageID
			+ "::" + String.valueOf(aDProcessParaID);
	}

	public int hashCode() {
		int rs = 17;
		rs = rs * 37 + ((aDLanguageID == null) ? 0 : aDLanguageID.hashCode());
		rs = rs * 37 + ((aDProcessParaID == null) ? 0 : aDProcessParaID.hashCode());
		return rs;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		ADProcessParaTrlPK other = (ADProcessParaTrlPK) obj;
		return ((aDLanguageID == null && other.aDLanguageID == null)
			|| (aDLanguageID != null && aDLanguageID.equals(other.aDLanguageID)))
			&& ((aDProcessParaID == null && other.aDProcessParaID == null)
			|| (aDProcessParaID != null && aDProcessParaID.equals(other.aDProcessParaID)));
	}

	private void fromString(String str) {
		Tokenizer toke = new Tokenizer(str);
		str = toke.nextToken();
		if("null".equals(str))
			aDLanguageID = null;
		else
			aDLanguageID = new Integer(str);
		str = toke.nextToken();
		if("null".equals(str))
			aDProcessParaID = null;
		else
			aDProcessParaID = new Integer(str);
	}

	protected static class Tokenizer {
		private final String str;
		private int last;

		public Tokenizer (String str) {
			this.str = str;
		}

		public String nextToken () {
			int next = str.indexOf("::", last);
			String part;
			if(next == -1) {
				part = str.substring(last);
				last = str.length();
			} else {
				part = str.substring(last, next);
				last = next + 2;
			}
			return part;
		}
	}
}