package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by: org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name = "ad_ref_table")
public class AdRefTable extends org.adempiere.common.ADEntityBase {
	private static final long	serialVersionUID	= 1L;
	private Integer				adClientId;
	private Integer				adDisplay;
	private Integer				adKey;
	private Integer				adOrgId;
	private Integer				adReferenceId;
	private Integer				adTableId;
	private Integer				adWindowId;
	private String				created;
	private Integer				createdby;
	private String				entitytype;
	private String				isactive;
	private String				isvaluedisplayed;
	private String				orderbyclause;
	private String				updated;
	private Integer				updatedby;
	private String				whereclause;
	private AdReference         adReference;
	private AdColumn			keyColumn;
	private AdColumn			displayColumn;
	private AdTable				adTable;

	public AdRefTable() {
	}

	public AdRefTable(Integer adReferenceId) {
		this.adReferenceId = adReferenceId;
	}

	@Basic
	@Column(name = "AD_CLIENT_ID", nullable = false)
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name = "AD_DISPLAY", nullable = false)
	public Integer getAdDisplay() {
		return adDisplay;
	}

	public void setAdDisplay(Integer adDisplay) {
		this.adDisplay = adDisplay;
	}

	@Basic
	@Column(name = "AD_KEY", nullable = false)
	public Integer getAdKey() {
		return adKey;
	}

	public void setAdKey(Integer adKey) {
		this.adKey = adKey;
	}

	@Basic
	@Column(name = "AD_ORG_ID", nullable = false)
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Id
	@Column(name = "AD_REFERENCE_ID")
	public Integer getAdReferenceId() {
		return adReferenceId;
	}

	public void setAdReferenceId(Integer adReferenceId) {
		this.adReferenceId = adReferenceId;
	}

	@Basic
	@Column(name = "AD_TABLE_ID", nullable = false)
	public Integer getAdTableId() {
		return adTableId;
	}

	public void setAdTableId(Integer adTableId) {
		this.adTableId = adTableId;
	}

	@Basic
	@Column(name = "AD_WINDOW_ID")
	public Integer getAdWindowId() {
		return adWindowId;
	}

	public void setAdWindowId(Integer adWindowId) {
		this.adWindowId = adWindowId;
	}

	@Basic
	@Column(columnDefinition = "TIMESTAMP", nullable = false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(nullable = false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(nullable = false, length = 40)
	public String getEntitytype() {
		return entitytype;
	}

	public void setEntitytype(String entitytype) {
		this.entitytype = entitytype;
	}

	@Basic
	@Column(nullable = false, length = 1)
	public String getIsactive() {
		return isactive;
	}

	public void setIsactive(String isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(nullable = false, length = 1)
	public String getIsvaluedisplayed() {
		return isvaluedisplayed;
	}

	public void setIsvaluedisplayed(String isvaluedisplayed) {
		this.isvaluedisplayed = isvaluedisplayed;
	}

	@Basic
	@Column(length = 2000)
	public String getOrderbyclause() {
		return orderbyclause;
	}

	public void setOrderbyclause(String orderbyclause) {
		this.orderbyclause = orderbyclause;
	}

	@Basic
	@Column(columnDefinition = "TIMESTAMP", nullable = false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(nullable = false)
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	@Basic
	@Column(length = 2000)
	public String getWhereclause() {
		return whereclause;
	}

	public void setWhereclause(String whereclause) {
		this.whereclause = whereclause;
	}

	// bi-directional one-to-one association to AdReference
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AD_REFERENCE_ID")
	public AdReference getAdReference() {
		return this.adReference;
	}

	public void setAdReference(AdReference adReference) {
		this.adReference = adReference;
	}

	// uni-directional one-to-one association to AdColumn
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AD_KEY")
	public AdColumn getKeyColumn() {
		return this.keyColumn;
	}

	public void setKeyColumn(AdColumn keyColumn) {
		this.keyColumn = keyColumn;
	}

	// uni-directional one-to-one association to AdColumn
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AD_DISPLAY")
	public AdColumn getDisplayColumn() {
		return this.displayColumn;
	}

	public void setDisplayColumn(AdColumn displayColumn) {
		this.displayColumn = displayColumn;
	}

	// uni-directional one-to-one association to AdTable
	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AD_TABLE_ID")
	public AdTable getAdTable() {
		return this.adTable;
	}

	public void setAdTable(AdTable adTable) {
		this.adTable = adTable;
	}
}