package org.adempiere.model;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: org.adempiere.model.ADSequenceAudit
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class ADSequenceAuditPK implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("org.adempiere.model.ADSequenceAudit"); }
		catch(Exception e) {}
	}

	public Integer aDSequenceID;
	public String documentNo;

	public ADSequenceAuditPK() {
	}

	public ADSequenceAuditPK(String str) {
		fromString(str);
	}

	public Integer getADSequenceID() {
		return aDSequenceID;
	}

	public void setADSequenceID(Integer aDSequenceID) {
		this.aDSequenceID = aDSequenceID;
	}

	public String getDocumentNo() {
		return documentNo;
	}

	public void setDocumentNo(String documentNo) {
		this.documentNo = documentNo;
	}

	public String toString() {
		return String.valueOf(aDSequenceID)
			+ "::" + documentNo;
	}

	public int hashCode() {
		int rs = 17;
		rs = rs * 37 + ((aDSequenceID == null) ? 0 : aDSequenceID.hashCode());
		rs = rs * 37 + ((documentNo == null) ? 0 : documentNo.hashCode());
		return rs;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		ADSequenceAuditPK other = (ADSequenceAuditPK) obj;
		return ((aDSequenceID == null && other.aDSequenceID == null)
			|| (aDSequenceID != null && aDSequenceID.equals(other.aDSequenceID)))
			&& ((documentNo == null && other.documentNo == null)
			|| (documentNo != null && documentNo.equals(other.documentNo)));
	}

	private void fromString(String str) {
		Tokenizer toke = new Tokenizer(str);
		str = toke.nextToken();
		if("null".equals(str))
			aDSequenceID = null;
		else
			aDSequenceID = new Integer(str);
		str = toke.nextToken();
		if("null".equals(str))
			documentNo = null;
		else
			documentNo = str;
	}

	protected static class Tokenizer {
		private final String str;
		private int last;

		public Tokenizer (String str) {
			this.str = str;
		}

		public String nextToken () {
			int next = str.indexOf("::", last);
			String part;
			if(next == -1) {
				part = str.substring(last);
				last = str.length();
			} else {
				part = str.substring(last, next);
				last = next + 2;
			}
			return part;
		}
	}
}