package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="ad_table_access")
@IdClass(org.adempiere.model.ADTableAccessPK.class)
public class ADTableAccess extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private Integer aDOrgID;
	private Integer aDRoleID;
	private Integer aDTableID;
	private String accessTypeRule;
	private Boolean active;
	private Boolean canExport;
	private Boolean canReport;
	private String created;
	private Integer createdBy;
	private Boolean exclude;
	private Boolean readOnly;
	private String updated;
	private Integer updatedBy;

	public ADTableAccess() {
	}

	public ADTableAccess(Integer aDRoleID, Integer aDTableID, String accessTypeRule) {
		this.aDRoleID = aDRoleID;
		this.aDTableID = aDTableID;
		this.accessTypeRule = accessTypeRule;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Id
	@Column(name="AD_ROLE_ID", columnDefinition="INT")
	public Integer getADRoleID() {
		return aDRoleID;
	}

	public void setADRoleID(Integer aDRoleID) {
		this.aDRoleID = aDRoleID;
	}

	@Id
	@Column(name="AD_TABLE_ID", columnDefinition="INT")
	public Integer getADTableID() {
		return aDTableID;
	}

	public void setADTableID(Integer aDTableID) {
		this.aDTableID = aDTableID;
	}

	@Id
	@Column(length=1)
	public String getAccessTypeRule() {
		return accessTypeRule;
	}

	public void setAccessTypeRule(String accessTypeRule) {
		this.accessTypeRule = accessTypeRule;
	}

	@Basic
	@Column(name="ISACTIVE", nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(name="ISCANEXPORT", nullable=false)
	public Boolean isCanExport() {
		return canExport;
	}

	public void setCanExport(Boolean canExport) {
		this.canExport = canExport;
	}

	@Basic
	@Column(name="ISCANREPORT", nullable=false)
	public Boolean isCanReport() {
		return canReport;
	}

	public void setCanReport(Boolean canReport) {
		this.canReport = canReport;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	@Column(name="ISEXCLUDE", nullable=false)
	public Boolean isExclude() {
		return exclude;
	}

	public void setExclude(Boolean exclude) {
		this.exclude = exclude;
	}

	@Basic
	@Column(name="ISREADONLY", nullable=false)
	public Boolean isReadOnly() {
		return readOnly;
	}

	public void setReadOnly(Boolean readOnly) {
		this.readOnly = readOnly;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}
}