package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="ad_table_scriptvalidator")
public class ADTableScriptValidator extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private Integer aDOrgID;
	private Integer aDRuleID;
	private Integer aDTableID;
	private Integer aDTableScriptValidatorID;
	private Boolean active;
	private String created;
	private Integer createdBy;
	private String eventModelValidator;
	private Integer seqNo;
	private String updated;
	private Integer updatedBy;

	public ADTableScriptValidator() {
	}

	public ADTableScriptValidator(Integer aDTableScriptValidatorID) {
		this.aDTableScriptValidatorID = aDTableScriptValidatorID;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Basic
	@Column(name="AD_RULE_ID", columnDefinition="INT", nullable=false)
	public Integer getADRuleID() {
		return aDRuleID;
	}

	public void setADRuleID(Integer aDRuleID) {
		this.aDRuleID = aDRuleID;
	}

	@Basic
	@Column(name="AD_TABLE_ID", columnDefinition="INT", nullable=false)
	public Integer getADTableID() {
		return aDTableID;
	}

	public void setADTableID(Integer aDTableID) {
		this.aDTableID = aDTableID;
	}

	@Id
	@Column(name="AD_TABLE_SCRIPTVALIDATOR_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_53076", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "AD_Table_ScriptValidator", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_53076")
	public Integer getADTableScriptValidatorID() {
		return aDTableScriptValidatorID;
	}

	public void setADTableScriptValidatorID(Integer aDTableScriptValidatorID) {
		this.aDTableScriptValidatorID = aDTableScriptValidatorID;
	}

	@Basic
	@Column(name="ISACTIVE", nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	@Column(nullable=false, length=4)
	public String getEventModelValidator() {
		return eventModelValidator;
	}

	public void setEventModelValidator(String eventModelValidator) {
		this.eventModelValidator = eventModelValidator;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getSeqNo() {
		return seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}
}