package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="ad_userdef_field")
public class ADUserDefField extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private Integer aDFieldID;
	private Integer aDOrgID;
	private Integer aDUserDefFieldID;
	private Integer aDUserDefTabID;
	private Boolean active;
	private String created;
	private Integer createdBy;
	private String defaultValue;
	private String description;
	private Integer displayLength;
	private String displayLogic;
	private Boolean displayed;
	private String help;
	private String name;
	private Boolean readOnly;
	private Boolean sameLine;
	private Integer seqNo;
	private Integer sortNo;
	private Boolean updateable;
	private String updated;
	private Integer updatedBy;

	public ADUserDefField() {
	}

	public ADUserDefField(Integer aDUserDefFieldID) {
		this.aDUserDefFieldID = aDUserDefFieldID;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name="AD_FIELD_ID", columnDefinition="INT", nullable=false)
	public Integer getADFieldID() {
		return aDFieldID;
	}

	public void setADFieldID(Integer aDFieldID) {
		this.aDFieldID = aDFieldID;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Id
	@Column(name="AD_USERDEF_FIELD_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_539", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "AD_UserDef_Field", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_539")
	public Integer getADUserDefFieldID() {
		return aDUserDefFieldID;
	}

	public void setADUserDefFieldID(Integer aDUserDefFieldID) {
		this.aDUserDefFieldID = aDUserDefFieldID;
	}

	@Basic
	@Column(name="AD_USERDEF_TAB_ID", columnDefinition="INT", nullable=false)
	public Integer getADUserDefTabID() {
		return aDUserDefTabID;
	}

	public void setADUserDefTabID(Integer aDUserDefTabID) {
		this.aDUserDefTabID = aDUserDefTabID;
	}

	@Basic
	@Column(name="ISACTIVE", nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	@Column(nullable=false, length=2000)
	public String getDefaultValue() {
		return defaultValue;
	}

	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getDisplayLength() {
		return displayLength;
	}

	public void setDisplayLength(Integer displayLength) {
		this.displayLength = displayLength;
	}

	@Basic
	@Column(nullable=false, length=2000)
	public String getDisplayLogic() {
		return displayLogic;
	}

	public void setDisplayLogic(String displayLogic) {
		this.displayLogic = displayLogic;
	}

	@Basic
	@Column(name="ISDISPLAYED", nullable=false)
	public Boolean isDisplayed() {
		return displayed;
	}

	public void setDisplayed(Boolean displayed) {
		this.displayed = displayed;
	}

	@Basic
	@Column(length=2000)
	public String getHelp() {
		return help;
	}

	public void setHelp(String help) {
		this.help = help;
	}

	@Basic
	@Column(nullable=false, length=60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	@Column(name="ISREADONLY", nullable=false)
	public Boolean isReadOnly() {
		return readOnly;
	}

	public void setReadOnly(Boolean readOnly) {
		this.readOnly = readOnly;
	}

	@Basic
	@Column(name="ISSAMELINE", nullable=false)
	public Boolean isSameLine() {
		return sameLine;
	}

	public void setSameLine(Boolean sameLine) {
		this.sameLine = sameLine;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getSeqNo() {
		return seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getSortNo() {
		return sortNo;
	}

	public void setSortNo(Integer sortNo) {
		this.sortNo = sortNo;
	}

	@Basic
	@Column(name="ISUPDATEABLE", nullable=false)
	public Boolean isUpdateable() {
		return updateable;
	}

	public void setUpdateable(Boolean updateable) {
		this.updateable = updateable;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}
}