package org.adempiere.model;

import java.math.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="ad_wf_node")
public class AdWfNode extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private String action;
	private Integer adClientId;
	private Integer adColumnId;
	private Integer adFormId;
	private Integer adImageId;
	private Integer adOrgId;
	private Integer adProcessId;
	private Integer adTaskId;
	private Integer adWfBlockId;
	private Integer adWfNodeId;
	private Integer adWfResponsibleId;
	private Integer adWindowId;
	private Integer adWorkflowId;
	private String attributename;
	private String attributevalue;
	private Integer cBpartnerId;
	private BigDecimal cost;
	private String created;
	private Integer createdby;
	private String description;
	private String docaction;
	private Integer duration;
	private BigDecimal dynprioritychange;
	private String dynpriorityunit;
	private String email;
	private String emailrecipient;
	private String entitytype;
	private String finishmode;
	private String help;
	private Boolean isactive;
	private Boolean iscentrallymaintained;
	private Boolean ismilestone;
	private Boolean issubcontracting;
	private String joinelement;
	private Integer limit;
	private Integer movingtime;
	private String name;
	private Integer overlapunits;
	private Integer priority;
	private Integer queuingtime;
	private Integer rMailtextId;
	private Integer sResourceId;
	private Integer setuptime;
	private String splitelement;
	private String startmode;
	private String subflowexecution;
	private BigDecimal unitscycles;
	private String updated;
	private Integer updatedby;
	private String validfrom;
	private String validto;
	private String value;
	private Integer waitingtime;
	private Integer waittime;
	private Integer workflowId;
	private Integer workingtime;
	private Integer xposition;
	private Integer yield;
	private Integer yposition;

	public AdWfNode() {
	}

	public AdWfNode(Integer adWfNodeId) {
		this.adWfNodeId = adWfNodeId;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name="AD_COLUMN_ID", columnDefinition="INT")
	public Integer getAdColumnId() {
		return adColumnId;
	}

	public void setAdColumnId(Integer adColumnId) {
		this.adColumnId = adColumnId;
	}

	@Basic
	@Column(name="AD_FORM_ID", columnDefinition="INT")
	public Integer getAdFormId() {
		return adFormId;
	}

	public void setAdFormId(Integer adFormId) {
		this.adFormId = adFormId;
	}

	@Basic
	@Column(name="AD_IMAGE_ID", columnDefinition="INT")
	public Integer getAdImageId() {
		return adImageId;
	}

	public void setAdImageId(Integer adImageId) {
		this.adImageId = adImageId;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Basic
	@Column(name="AD_PROCESS_ID", columnDefinition="INT")
	public Integer getAdProcessId() {
		return adProcessId;
	}

	public void setAdProcessId(Integer adProcessId) {
		this.adProcessId = adProcessId;
	}

	@Basic
	@Column(name="AD_TASK_ID", columnDefinition="INT")
	public Integer getAdTaskId() {
		return adTaskId;
	}

	public void setAdTaskId(Integer adTaskId) {
		this.adTaskId = adTaskId;
	}

	@Basic
	@Column(name="AD_WF_BLOCK_ID", columnDefinition="INT")
	public Integer getAdWfBlockId() {
		return adWfBlockId;
	}

	public void setAdWfBlockId(Integer adWfBlockId) {
		this.adWfBlockId = adWfBlockId;
	}

	@Id
	@Column(name="AD_WF_NODE_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_32", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "AD_WF_Node", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_32")
	public Integer getAdWfNodeId() {
		return adWfNodeId;
	}

	public void setAdWfNodeId(Integer adWfNodeId) {
		this.adWfNodeId = adWfNodeId;
	}

	@Basic
	@Column(name="AD_WF_RESPONSIBLE_ID", columnDefinition="INT")
	public Integer getAdWfResponsibleId() {
		return adWfResponsibleId;
	}

	public void setAdWfResponsibleId(Integer adWfResponsibleId) {
		this.adWfResponsibleId = adWfResponsibleId;
	}

	@Basic
	@Column(name="AD_WINDOW_ID", columnDefinition="INT")
	public Integer getAdWindowId() {
		return adWindowId;
	}

	public void setAdWindowId(Integer adWindowId) {
		this.adWindowId = adWindowId;
	}

	@Basic
	@Column(name="AD_WORKFLOW_ID", columnDefinition="INT", nullable=false)
	public Integer getAdWorkflowId() {
		return adWorkflowId;
	}

	public void setAdWorkflowId(Integer adWorkflowId) {
		this.adWorkflowId = adWorkflowId;
	}

	@Basic
	@Column(length=60)
	public String getAttributename() {
		return attributename;
	}

	public void setAttributename(String attributename) {
		this.attributename = attributename;
	}

	@Basic
	@Column(length=60)
	public String getAttributevalue() {
		return attributevalue;
	}

	public void setAttributevalue(String attributevalue) {
		this.attributevalue = attributevalue;
	}

	@Basic
	@Column(name="C_BPARTNER_ID", columnDefinition="INT")
	public Integer getCBpartnerId() {
		return cBpartnerId;
	}

	public void setCBpartnerId(Integer cBpartnerId) {
		this.cBpartnerId = cBpartnerId;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getCost() {
		return cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(length=2)
	public String getDocaction() {
		return docaction;
	}

	public void setDocaction(String docaction) {
		this.docaction = docaction;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getDuration() {
		return duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Basic
	public BigDecimal getDynprioritychange() {
		return dynprioritychange;
	}

	public void setDynprioritychange(BigDecimal dynprioritychange) {
		this.dynprioritychange = dynprioritychange;
	}

	@Basic
	@Column(length=1)
	public String getDynpriorityunit() {
		return dynpriorityunit;
	}

	public void setDynpriorityunit(String dynpriorityunit) {
		this.dynpriorityunit = dynpriorityunit;
	}

	@Basic
	@Column(length=60)
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Basic
	@Column(length=1)
	public String getEmailrecipient() {
		return emailrecipient;
	}

	public void setEmailrecipient(String emailrecipient) {
		this.emailrecipient = emailrecipient;
	}

	@Basic
	@Column(nullable=false, length=40)
	public String getEntitytype() {
		return entitytype;
	}

	public void setEntitytype(String entitytype) {
		this.entitytype = entitytype;
	}

	@Basic
	@Column(length=1)
	public String getFinishmode() {
		return finishmode;
	}

	public void setFinishmode(String finishmode) {
		this.finishmode = finishmode;
	}

	@Basic
	@Column(length=2000)
	public String getHelp() {
		return help;
	}

	public void setHelp(String help) {
		this.help = help;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsactive() {
		return isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIscentrallymaintained() {
		return iscentrallymaintained;
	}

	public void setIscentrallymaintained(Boolean iscentrallymaintained) {
		this.iscentrallymaintained = iscentrallymaintained;
	}

	@Basic
	public Boolean isIsmilestone() {
		return ismilestone;
	}

	public void setIsmilestone(Boolean ismilestone) {
		this.ismilestone = ismilestone;
	}

	@Basic
	public Boolean isIssubcontracting() {
		return issubcontracting;
	}

	public void setIssubcontracting(Boolean issubcontracting) {
		this.issubcontracting = issubcontracting;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getJoinelement() {
		return joinelement;
	}

	public void setJoinelement(String joinelement) {
		this.joinelement = joinelement;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getLimit() {
		return limit;
	}

	public void setLimit(Integer limit) {
		this.limit = limit;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getMovingtime() {
		return movingtime;
	}

	public void setMovingtime(Integer movingtime) {
		this.movingtime = movingtime;
	}

	@Basic
	@Column(nullable=false, length=60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getOverlapunits() {
		return overlapunits;
	}

	public void setOverlapunits(Integer overlapunits) {
		this.overlapunits = overlapunits;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getPriority() {
		return priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getQueuingtime() {
		return queuingtime;
	}

	public void setQueuingtime(Integer queuingtime) {
		this.queuingtime = queuingtime;
	}

	@Basic
	@Column(name="R_MAILTEXT_ID", columnDefinition="INT")
	public Integer getRMailtextId() {
		return rMailtextId;
	}

	public void setRMailtextId(Integer rMailtextId) {
		this.rMailtextId = rMailtextId;
	}

	@Basic
	@Column(name="S_RESOURCE_ID", columnDefinition="INT")
	public Integer getSResourceId() {
		return sResourceId;
	}

	public void setSResourceId(Integer sResourceId) {
		this.sResourceId = sResourceId;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getSetuptime() {
		return setuptime;
	}

	public void setSetuptime(Integer setuptime) {
		this.setuptime = setuptime;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getSplitelement() {
		return splitelement;
	}

	public void setSplitelement(String splitelement) {
		this.splitelement = splitelement;
	}

	@Basic
	@Column(length=1)
	public String getStartmode() {
		return startmode;
	}

	public void setStartmode(String startmode) {
		this.startmode = startmode;
	}

	@Basic
	@Column(length=1)
	public String getSubflowexecution() {
		return subflowexecution;
	}

	public void setSubflowexecution(String subflowexecution) {
		this.subflowexecution = subflowexecution;
	}

	@Basic
	public BigDecimal getUnitscycles() {
		return unitscycles;
	}

	public void setUnitscycles(BigDecimal unitscycles) {
		this.unitscycles = unitscycles;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	@Basic
	public String getValidfrom() {
		return validfrom;
	}

	public void setValidfrom(String validfrom) {
		this.validfrom = validfrom;
	}

	@Basic
	public String getValidto() {
		return validto;
	}

	public void setValidto(String validto) {
		this.validto = validto;
	}

	@Basic
	@Column(nullable=false, length=40)
	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getWaitingtime() {
		return waitingtime;
	}

	public void setWaitingtime(Integer waitingtime) {
		this.waitingtime = waitingtime;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getWaittime() {
		return waittime;
	}

	public void setWaittime(Integer waittime) {
		this.waittime = waittime;
	}

	@Basic
	@Column(name="WORKFLOW_ID", columnDefinition="INT")
	public Integer getWorkflowId() {
		return workflowId;
	}

	public void setWorkflowId(Integer workflowId) {
		this.workflowId = workflowId;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getWorkingtime() {
		return workingtime;
	}

	public void setWorkingtime(Integer workingtime) {
		this.workingtime = workingtime;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getXposition() {
		return xposition;
	}

	public void setXposition(Integer xposition) {
		this.xposition = xposition;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getYield() {
		return yield;
	}

	public void setYield(Integer yield) {
		this.yield = yield;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getYposition() {
		return yposition;
	}

	public void setYposition(Integer yposition) {
		this.yposition = yposition;
	}
}