package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="c_bp_relation")
public class CBpRelation extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer adClientId;
	private Integer adOrgId;
	private Integer cBpRelationId;
	private Integer cBpartnerId;
	private Integer cBpartnerLocationId;
	private Integer cBpartnerrelationId;
	private Integer cBpartnerrelationLocationId;
	private String created;
	private Integer createdby;
	private String description;
	private String isactive;
	private String isbillto;
	private String ispayfrom;
	private String isremitto;
	private String isshipto;
	private String name;
	private String updated;
	private Integer updatedby;

	public CBpRelation() {
	}

	public CBpRelation(Integer cBpRelationId) {
		this.cBpRelationId = cBpRelationId;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", nullable=false)
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name="AD_ORG_ID", nullable=false)
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Id
	@Column(name="C_BP_RELATION_ID")
	public Integer getCBpRelationId() {
		return cBpRelationId;
	}

	public void setCBpRelationId(Integer cBpRelationId) {
		this.cBpRelationId = cBpRelationId;
	}

	@Basic
	@Column(name="C_BPARTNER_ID", nullable=false)
	public Integer getCBpartnerId() {
		return cBpartnerId;
	}

	public void setCBpartnerId(Integer cBpartnerId) {
		this.cBpartnerId = cBpartnerId;
	}

	@Basic
	@Column(name="C_BPARTNER_LOCATION_ID")
	public Integer getCBpartnerLocationId() {
		return cBpartnerLocationId;
	}

	public void setCBpartnerLocationId(Integer cBpartnerLocationId) {
		this.cBpartnerLocationId = cBpartnerLocationId;
	}

	@Basic
	@Column(name="C_BPARTNERRELATION_ID", nullable=false)
	public Integer getCBpartnerrelationId() {
		return cBpartnerrelationId;
	}

	public void setCBpartnerrelationId(Integer cBpartnerrelationId) {
		this.cBpartnerrelationId = cBpartnerrelationId;
	}

	@Basic
	@Column(name="C_BPARTNERRELATION_LOCATION_ID", nullable=false)
	public Integer getCBpartnerrelationLocationId() {
		return cBpartnerrelationLocationId;
	}

	public void setCBpartnerrelationLocationId(Integer cBpartnerrelationLocationId) {
		this.cBpartnerrelationLocationId = cBpartnerrelationLocationId;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getIsactive() {
		return isactive;
	}

	public void setIsactive(String isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getIsbillto() {
		return isbillto;
	}

	public void setIsbillto(String isbillto) {
		this.isbillto = isbillto;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getIspayfrom() {
		return ispayfrom;
	}

	public void setIspayfrom(String ispayfrom) {
		this.ispayfrom = ispayfrom;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getIsremitto() {
		return isremitto;
	}

	public void setIsremitto(String isremitto) {
		this.isremitto = isremitto;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getIsshipto() {
		return isshipto;
	}

	public void setIsshipto(String isshipto) {
		this.isshipto = isshipto;
	}

	@Basic
	@Column(nullable=false, length=60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(nullable=false)
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}