package org.adempiere.model;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: org.adempiere.model.CCashBookAcct
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class CCashBookAcctPK implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("org.adempiere.model.CCashBookAcct"); }
		catch(Exception e) {}
	}

	public Integer cAcctSchemaID;
	public Integer cCashBookID;

	public CCashBookAcctPK() {
	}

	public CCashBookAcctPK(String str) {
		fromString(str);
	}

	public Integer getCAcctSchemaID() {
		return cAcctSchemaID;
	}

	public void setCAcctSchemaID(Integer cAcctSchemaID) {
		this.cAcctSchemaID = cAcctSchemaID;
	}

	public Integer getCCashBookID() {
		return cCashBookID;
	}

	public void setCCashBookID(Integer cCashBookID) {
		this.cCashBookID = cCashBookID;
	}

	public String toString() {
		return String.valueOf(cAcctSchemaID)
			+ "::" + String.valueOf(cCashBookID);
	}

	public int hashCode() {
		int rs = 17;
		rs = rs * 37 + ((cAcctSchemaID == null) ? 0 : cAcctSchemaID.hashCode());
		rs = rs * 37 + ((cCashBookID == null) ? 0 : cCashBookID.hashCode());
		return rs;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		CCashBookAcctPK other = (CCashBookAcctPK) obj;
		return ((cAcctSchemaID == null && other.cAcctSchemaID == null)
			|| (cAcctSchemaID != null && cAcctSchemaID.equals(other.cAcctSchemaID)))
			&& ((cCashBookID == null && other.cCashBookID == null)
			|| (cCashBookID != null && cCashBookID.equals(other.cCashBookID)));
	}

	private void fromString(String str) {
		Tokenizer toke = new Tokenizer(str);
		str = toke.nextToken();
		if("null".equals(str))
			cAcctSchemaID = null;
		else
			cAcctSchemaID = new Integer(str);
		str = toke.nextToken();
		if("null".equals(str))
			cCashBookID = null;
		else
			cCashBookID = new Integer(str);
	}

	protected static class Tokenizer {
		private final String str;
		private int last;

		public Tokenizer (String str) {
			this.str = str;
		}

		public String nextToken () {
			int next = str.indexOf("::", last);
			String part;
			if(next == -1) {
				part = str.substring(last);
				last = str.length();
			} else {
				part = str.substring(last, next);
				last = next + 2;
			}
			return part;
		}
	}
}