package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="c_cashbook_acct")
@IdClass(org.adempiere.model.CCashbookAcctPK.class)
public class CCashbookAcct extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer adClientId;
	private Integer adOrgId;
	private Integer cAcctschemaId;
	private Integer cCashbookId;
	private Integer cbAssetAcct;
	private Integer cbCashtransferAcct;
	private Integer cbDifferencesAcct;
	private Integer cbExpenseAcct;
	private Integer cbReceiptAcct;
	private String created;
	private Integer createdby;
	private Boolean isactive;
	private String updated;
	private Integer updatedby;

	public CCashbookAcct() {
	}

	public CCashbookAcct(Integer cAcctschemaId, Integer cCashbookId) {
		this.cAcctschemaId = cAcctschemaId;
		this.cCashbookId = cCashbookId;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Id
	@Column(name="C_ACCTSCHEMA_ID", columnDefinition="INT")
	public Integer getCAcctschemaId() {
		return cAcctschemaId;
	}

	public void setCAcctschemaId(Integer cAcctschemaId) {
		this.cAcctschemaId = cAcctschemaId;
	}

	@Id
	@Column(name="C_CASHBOOK_ID", columnDefinition="INT")
	public Integer getCCashbookId() {
		return cCashbookId;
	}

	public void setCCashbookId(Integer cCashbookId) {
		this.cCashbookId = cCashbookId;
	}

	@Basic
	@Column(name="CB_ASSET_ACCT", columnDefinition="INT", nullable=false)
	public Integer getCbAssetAcct() {
		return cbAssetAcct;
	}

	public void setCbAssetAcct(Integer cbAssetAcct) {
		this.cbAssetAcct = cbAssetAcct;
	}

	@Basic
	@Column(name="CB_CASHTRANSFER_ACCT", columnDefinition="INT", nullable=false)
	public Integer getCbCashtransferAcct() {
		return cbCashtransferAcct;
	}

	public void setCbCashtransferAcct(Integer cbCashtransferAcct) {
		this.cbCashtransferAcct = cbCashtransferAcct;
	}

	@Basic
	@Column(name="CB_DIFFERENCES_ACCT", columnDefinition="INT", nullable=false)
	public Integer getCbDifferencesAcct() {
		return cbDifferencesAcct;
	}

	public void setCbDifferencesAcct(Integer cbDifferencesAcct) {
		this.cbDifferencesAcct = cbDifferencesAcct;
	}

	@Basic
	@Column(name="CB_EXPENSE_ACCT", columnDefinition="INT", nullable=false)
	public Integer getCbExpenseAcct() {
		return cbExpenseAcct;
	}

	public void setCbExpenseAcct(Integer cbExpenseAcct) {
		this.cbExpenseAcct = cbExpenseAcct;
	}

	@Basic
	@Column(name="CB_RECEIPT_ACCT", columnDefinition="INT", nullable=false)
	public Integer getCbReceiptAcct() {
		return cbReceiptAcct;
	}

	public void setCbReceiptAcct(Integer cbReceiptAcct) {
		this.cbReceiptAcct = cbReceiptAcct;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsactive() {
		return isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}