package org.adempiere.model;

import java.math.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="c_commissionamt")
public class CCommissionamt extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private BigDecimal actualqty;
	private Integer adClientId;
	private Integer adOrgId;
	private Integer cCommissionamtId;
	private Integer cCommissionlineId;
	private Integer cCommissionrunId;
	private BigDecimal commissionamt;
	private BigDecimal convertedamt;
	private String created;
	private Integer createdby;
	private Boolean isactive;
	private String updated;
	private Integer updatedby;

	public CCommissionamt() {
	}

	public CCommissionamt(Integer cCommissionamtId) {
		this.cCommissionamtId = cCommissionamtId;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getActualqty() {
		return actualqty;
	}

	public void setActualqty(BigDecimal actualqty) {
		this.actualqty = actualqty;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Id
	@Column(name="C_COMMISSIONAMT_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_367", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "C_CommissionAmt", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_367")
	public Integer getCCommissionamtId() {
		return cCommissionamtId;
	}

	public void setCCommissionamtId(Integer cCommissionamtId) {
		this.cCommissionamtId = cCommissionamtId;
	}

	@Basic
	@Column(name="C_COMMISSIONLINE_ID", columnDefinition="INT", nullable=false)
	public Integer getCCommissionlineId() {
		return cCommissionlineId;
	}

	public void setCCommissionlineId(Integer cCommissionlineId) {
		this.cCommissionlineId = cCommissionlineId;
	}

	@Basic
	@Column(name="C_COMMISSIONRUN_ID", columnDefinition="INT", nullable=false)
	public Integer getCCommissionrunId() {
		return cCommissionrunId;
	}

	public void setCCommissionrunId(Integer cCommissionrunId) {
		this.cCommissionrunId = cCommissionrunId;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getCommissionamt() {
		return commissionamt;
	}

	public void setCommissionamt(BigDecimal commissionamt) {
		this.commissionamt = commissionamt;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getConvertedamt() {
		return convertedamt;
	}

	public void setConvertedamt(BigDecimal convertedamt) {
		this.convertedamt = convertedamt;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsactive() {
		return isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}