package org.adempiere.model;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: org.adempiere.model.CCyclePhase
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class CCyclePhasePK implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("org.adempiere.model.CCyclePhase"); }
		catch(Exception e) {}
	}

	public Integer cCycleStepID;
	public Integer cPhaseID;

	public CCyclePhasePK() {
	}

	public CCyclePhasePK(String str) {
		fromString(str);
	}

	public Integer getCCycleStepID() {
		return cCycleStepID;
	}

	public void setCCycleStepID(Integer cCycleStepID) {
		this.cCycleStepID = cCycleStepID;
	}

	public Integer getCPhaseID() {
		return cPhaseID;
	}

	public void setCPhaseID(Integer cPhaseID) {
		this.cPhaseID = cPhaseID;
	}

	public String toString() {
		return String.valueOf(cCycleStepID)
			+ "::" + String.valueOf(cPhaseID);
	}

	public int hashCode() {
		int rs = 17;
		rs = rs * 37 + ((cCycleStepID == null) ? 0 : cCycleStepID.hashCode());
		rs = rs * 37 + ((cPhaseID == null) ? 0 : cPhaseID.hashCode());
		return rs;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		CCyclePhasePK other = (CCyclePhasePK) obj;
		return ((cCycleStepID == null && other.cCycleStepID == null)
			|| (cCycleStepID != null && cCycleStepID.equals(other.cCycleStepID)))
			&& ((cPhaseID == null && other.cPhaseID == null)
			|| (cPhaseID != null && cPhaseID.equals(other.cPhaseID)));
	}

	private void fromString(String str) {
		Tokenizer toke = new Tokenizer(str);
		str = toke.nextToken();
		if("null".equals(str))
			cCycleStepID = null;
		else
			cCycleStepID = new Integer(str);
		str = toke.nextToken();
		if("null".equals(str))
			cPhaseID = null;
		else
			cPhaseID = new Integer(str);
	}

	protected static class Tokenizer {
		private final String str;
		private int last;

		public Tokenizer (String str) {
			this.str = str;
		}

		public String nextToken () {
			int next = str.indexOf("::", last);
			String part;
			if(next == -1) {
				part = str.substring(last);
				last = str.length();
			} else {
				part = str.substring(last, next);
				last = next + 2;
			}
			return part;
		}
	}
}