package org.adempiere.model;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: org.adempiere.model.CMAccessListRole
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class CMAccessListRolePK implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("org.adempiere.model.CMAccessListRole"); }
		catch(Exception e) {}
	}

	public Integer aDRoleID;
	public Integer cMAccessProfileID;

	public CMAccessListRolePK() {
	}

	public CMAccessListRolePK(String str) {
		fromString(str);
	}

	public Integer getADRoleID() {
		return aDRoleID;
	}

	public void setADRoleID(Integer aDRoleID) {
		this.aDRoleID = aDRoleID;
	}

	public Integer getCMAccessProfileID() {
		return cMAccessProfileID;
	}

	public void setCMAccessProfileID(Integer cMAccessProfileID) {
		this.cMAccessProfileID = cMAccessProfileID;
	}

	public String toString() {
		return String.valueOf(aDRoleID)
			+ "::" + String.valueOf(cMAccessProfileID);
	}

	public int hashCode() {
		int rs = 17;
		rs = rs * 37 + ((aDRoleID == null) ? 0 : aDRoleID.hashCode());
		rs = rs * 37 + ((cMAccessProfileID == null) ? 0 : cMAccessProfileID.hashCode());
		return rs;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		CMAccessListRolePK other = (CMAccessListRolePK) obj;
		return ((aDRoleID == null && other.aDRoleID == null)
			|| (aDRoleID != null && aDRoleID.equals(other.aDRoleID)))
			&& ((cMAccessProfileID == null && other.cMAccessProfileID == null)
			|| (cMAccessProfileID != null && cMAccessProfileID.equals(other.cMAccessProfileID)));
	}

	private void fromString(String str) {
		Tokenizer toke = new Tokenizer(str);
		str = toke.nextToken();
		if("null".equals(str))
			aDRoleID = null;
		else
			aDRoleID = new Integer(str);
		str = toke.nextToken();
		if("null".equals(str))
			cMAccessProfileID = null;
		else
			cMAccessProfileID = new Integer(str);
	}

	protected static class Tokenizer {
		private final String str;
		private int last;

		public Tokenizer (String str) {
			this.str = str;
		}

		public String nextToken () {
			int next = str.indexOf("::", last);
			String part;
			if(next == -1) {
				part = str.substring(last);
				last = str.length();
			} else {
				part = str.substring(last, next);
				last = next + 2;
			}
			return part;
		}
	}
}