package org.adempiere.model;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: org.adempiere.model.CmAccessstage
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class CmAccessstagePK implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("org.adempiere.model.CmAccessstage"); }
		catch(Exception e) {}
	}

	public Integer cmAccessprofileId;
	public Integer cmCstageId;

	public CmAccessstagePK() {
	}

	public CmAccessstagePK(String str) {
		fromString(str);
	}

	public Integer getCmAccessprofileId() {
		return cmAccessprofileId;
	}

	public void setCmAccessprofileId(Integer cmAccessprofileId) {
		this.cmAccessprofileId = cmAccessprofileId;
	}

	public Integer getCmCstageId() {
		return cmCstageId;
	}

	public void setCmCstageId(Integer cmCstageId) {
		this.cmCstageId = cmCstageId;
	}

	public String toString() {
		return String.valueOf(cmAccessprofileId)
			+ "::" + String.valueOf(cmCstageId);
	}

	public int hashCode() {
		int rs = 17;
		rs = rs * 37 + ((cmAccessprofileId == null) ? 0 : cmAccessprofileId.hashCode());
		rs = rs * 37 + ((cmCstageId == null) ? 0 : cmCstageId.hashCode());
		return rs;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		CmAccessstagePK other = (CmAccessstagePK) obj;
		return ((cmAccessprofileId == null && other.cmAccessprofileId == null)
			|| (cmAccessprofileId != null && cmAccessprofileId.equals(other.cmAccessprofileId)))
			&& ((cmCstageId == null && other.cmCstageId == null)
			|| (cmCstageId != null && cmCstageId.equals(other.cmCstageId)));
	}

	private void fromString(String str) {
		Tokenizer toke = new Tokenizer(str);
		str = toke.nextToken();
		if("null".equals(str))
			cmAccessprofileId = null;
		else
			cmAccessprofileId = new Integer(str);
		str = toke.nextToken();
		if("null".equals(str))
			cmCstageId = null;
		else
			cmCstageId = new Integer(str);
	}

	protected static class Tokenizer {
		private final String str;
		private int last;

		public Tokenizer (String str) {
			this.str = str;
		}

		public String nextToken () {
			int next = str.indexOf("::", last);
			String part;
			if(next == -1) {
				part = str.substring(last);
				last = str.length();
			} else {
				part = str.substring(last, next);
				last = next + 2;
			}
			return part;
		}
	}
}