package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="cm_media")
public class CmMedia extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer adClientId;
	private Integer adImageId;
	private Integer adOrgId;
	private Integer cmMediaId;
	private Integer cmWebprojectId;
	private String contenttext;
	private String created;
	private Integer createdby;
	private String description;
	private Boolean directdeploy;
	private String help;
	private Boolean isactive;
	private Boolean issummary;
	private String mediatype;
	private String name;
	private String updated;
	private Integer updatedby;

	public CmMedia() {
	}

	public CmMedia(Integer cmMediaId) {
		this.cmMediaId = cmMediaId;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name="AD_IMAGE_ID", columnDefinition="INT")
	public Integer getAdImageId() {
		return adImageId;
	}

	public void setAdImageId(Integer adImageId) {
		this.adImageId = adImageId;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Id
	@Column(name="CM_MEDIA_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_1238", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "CM_Media", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_1238")
	public Integer getCmMediaId() {
		return cmMediaId;
	}

	public void setCmMediaId(Integer cmMediaId) {
		this.cmMediaId = cmMediaId;
	}

	@Basic
	@Column(name="CM_WEBPROJECT_ID", columnDefinition="INT", nullable=false)
	public Integer getCmWebprojectId() {
		return cmWebprojectId;
	}

	public void setCmWebprojectId(Integer cmWebprojectId) {
		this.cmWebprojectId = cmWebprojectId;
	}

	@Basic
	@Column(columnDefinition="LONGTEXT")
	public String getContenttext() {
		return contenttext;
	}

	public void setContenttext(String contenttext) {
		this.contenttext = contenttext;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	public Boolean isDirectdeploy() {
		return directdeploy;
	}

	public void setDirectdeploy(Boolean directdeploy) {
		this.directdeploy = directdeploy;
	}

	@Basic
	@Column(length=2000)
	public String getHelp() {
		return help;
	}

	public void setHelp(String help) {
		this.help = help;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsactive() {
		return isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIssummary() {
		return issummary;
	}

	public void setIssummary(Boolean issummary) {
		this.issummary = issummary;
	}

	@Basic
	@Column(length=3)
	public String getMediatype() {
		return mediatype;
	}

	public void setMediatype(String mediatype) {
		this.mediatype = mediatype;
	}

	@Basic
	@Column(nullable=false, length=60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}