package org.adempiere.model;

import java.math.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="c_projectline")
public class CProjectLine extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private Integer aDOrgID;
	private Boolean active;
	private Integer cOrderID;
	private Integer cOrderPOID;
	private Integer cProjectID;
	private Integer cProjectIssueID;
	private Integer cProjectLineID;
	private Integer cProjectPhaseID;
	private Integer cProjectTaskID;
	private BigDecimal committedAmt;
	private BigDecimal committedQty;
	private String created;
	private Integer createdBy;
	private String description;
	private Boolean doPricing;
	private BigDecimal invoicedAmt;
	private BigDecimal invoicedQty;
	private Integer line;
	private Integer mProductCategoryID;
	private Integer mProductID;
	private BigDecimal plannedAmt;
	private BigDecimal plannedMarginAmt;
	private BigDecimal plannedPrice;
	private BigDecimal plannedQty;
	private Boolean printed;
	private Boolean processed;
	private String updated;
	private Integer updatedBy;

	public CProjectLine() {
	}

	public CProjectLine(Integer cProjectLineID) {
		this.cProjectLineID = cProjectLineID;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Basic
	@Column(name="ISACTIVE", nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(name="C_ORDER_ID", columnDefinition="INT")
	public Integer getCOrderID() {
		return cOrderID;
	}

	public void setCOrderID(Integer cOrderID) {
		this.cOrderID = cOrderID;
	}

	@Basic
	@Column(name="C_ORDERPO_ID", columnDefinition="INT")
	public Integer getCOrderPOID() {
		return cOrderPOID;
	}

	public void setCOrderPOID(Integer cOrderPOID) {
		this.cOrderPOID = cOrderPOID;
	}

	@Basic
	@Column(name="C_PROJECT_ID", columnDefinition="INT", nullable=false)
	public Integer getCProjectID() {
		return cProjectID;
	}

	public void setCProjectID(Integer cProjectID) {
		this.cProjectID = cProjectID;
	}

	@Basic
	@Column(name="C_PROJECTISSUE_ID", columnDefinition="INT")
	public Integer getCProjectIssueID() {
		return cProjectIssueID;
	}

	public void setCProjectIssueID(Integer cProjectIssueID) {
		this.cProjectIssueID = cProjectIssueID;
	}

	@Id
	@Column(name="C_PROJECTLINE_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_371", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "C_ProjectLine", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_371")
	public Integer getCProjectLineID() {
		return cProjectLineID;
	}

	public void setCProjectLineID(Integer cProjectLineID) {
		this.cProjectLineID = cProjectLineID;
	}

	@Basic
	@Column(name="C_PROJECTPHASE_ID", columnDefinition="INT")
	public Integer getCProjectPhaseID() {
		return cProjectPhaseID;
	}

	public void setCProjectPhaseID(Integer cProjectPhaseID) {
		this.cProjectPhaseID = cProjectPhaseID;
	}

	@Basic
	@Column(name="C_PROJECTTASK_ID", columnDefinition="INT")
	public Integer getCProjectTaskID() {
		return cProjectTaskID;
	}

	public void setCProjectTaskID(Integer cProjectTaskID) {
		this.cProjectTaskID = cProjectTaskID;
	}

	@Basic
	public BigDecimal getCommittedAmt() {
		return committedAmt;
	}

	public void setCommittedAmt(BigDecimal committedAmt) {
		this.committedAmt = committedAmt;
	}

	@Basic
	public BigDecimal getCommittedQty() {
		return committedQty;
	}

	public void setCommittedQty(BigDecimal committedQty) {
		this.committedQty = committedQty;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	public Boolean isDoPricing() {
		return doPricing;
	}

	public void setDoPricing(Boolean doPricing) {
		this.doPricing = doPricing;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getInvoicedAmt() {
		return invoicedAmt;
	}

	public void setInvoicedAmt(BigDecimal invoicedAmt) {
		this.invoicedAmt = invoicedAmt;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getInvoicedQty() {
		return invoicedQty;
	}

	public void setInvoicedQty(BigDecimal invoicedQty) {
		this.invoicedQty = invoicedQty;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getLine() {
		return line;
	}

	public void setLine(Integer line) {
		this.line = line;
	}

	@Basic
	@Column(name="M_PRODUCT_CATEGORY_ID", columnDefinition="INT")
	public Integer getMProductCategoryID() {
		return mProductCategoryID;
	}

	public void setMProductCategoryID(Integer mProductCategoryID) {
		this.mProductCategoryID = mProductCategoryID;
	}

	@Basic
	@Column(name="M_PRODUCT_ID", columnDefinition="INT")
	public Integer getMProductID() {
		return mProductID;
	}

	public void setMProductID(Integer mProductID) {
		this.mProductID = mProductID;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getPlannedAmt() {
		return plannedAmt;
	}

	public void setPlannedAmt(BigDecimal plannedAmt) {
		this.plannedAmt = plannedAmt;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getPlannedMarginAmt() {
		return plannedMarginAmt;
	}

	public void setPlannedMarginAmt(BigDecimal plannedMarginAmt) {
		this.plannedMarginAmt = plannedMarginAmt;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getPlannedPrice() {
		return plannedPrice;
	}

	public void setPlannedPrice(BigDecimal plannedPrice) {
		this.plannedPrice = plannedPrice;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getPlannedQty() {
		return plannedQty;
	}

	public void setPlannedQty(BigDecimal plannedQty) {
		this.plannedQty = plannedQty;
	}

	@Basic
	@Column(name="ISPRINTED", nullable=false)
	public Boolean isPrinted() {
		return printed;
	}

	public void setPrinted(Boolean printed) {
		this.printed = printed;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isProcessed() {
		return processed;
	}

	public void setProcessed(Boolean processed) {
		this.processed = processed;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}
}