package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="c_subscription_delivery")
public class CSubscriptionDelivery extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer adClientId;
	private Integer adOrgId;
	private Integer cSubscriptionDeliveryId;
	private Integer cSubscriptionId;
	private String created;
	private Integer createdby;
	private Boolean isactive;
	private String updated;
	private Integer updatedby;

	public CSubscriptionDelivery() {
	}

	public CSubscriptionDelivery(Integer cSubscriptionDeliveryId) {
		this.cSubscriptionDeliveryId = cSubscriptionDeliveryId;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Id
	@Column(name="C_SUBSCRIPTION_DELIVERY_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_842", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "C_Subscription_Delivery", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_842")
	public Integer getCSubscriptionDeliveryId() {
		return cSubscriptionDeliveryId;
	}

	public void setCSubscriptionDeliveryId(Integer cSubscriptionDeliveryId) {
		this.cSubscriptionDeliveryId = cSubscriptionDeliveryId;
	}

	@Basic
	@Column(name="C_SUBSCRIPTION_ID", columnDefinition="INT", nullable=false)
	public Integer getCSubscriptionId() {
		return cSubscriptionId;
	}

	public void setCSubscriptionId(Integer cSubscriptionId) {
		this.cSubscriptionId = cSubscriptionId;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsactive() {
		return isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}