package org.adempiere.model;

import java.math.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="gl_journalline")
public class GlJournalline extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aAssetGroupId;
	private Integer aAssetId;
	private String aCreateasset;
	private String aProcessed;
	private Integer adClientId;
	private Integer adOrgId;
	private BigDecimal amtacctcr;
	private BigDecimal amtacctdr;
	private BigDecimal amtsourcecr;
	private BigDecimal amtsourcedr;
	private Integer cConversiontypeId;
	private Integer cCurrencyId;
	private Integer cUomId;
	private Integer cValidcombinationId;
	private String created;
	private Integer createdby;
	private BigDecimal currencyrate;
	private String dateacct;
	private String description;
	private Integer glJournalId;
	private Integer glJournallineId;
	private String isactive;
	private String isgenerated;
	private Integer line;
	private String processed;
	private BigDecimal qty;
	private String updated;
	private Integer updatedby;

	public GlJournalline() {
	}

	public GlJournalline(Integer glJournallineId) {
		this.glJournallineId = glJournallineId;
	}

	@Basic
	@Column(name="A_ASSET_GROUP_ID")
	public Integer getAAssetGroupId() {
		return aAssetGroupId;
	}

	public void setAAssetGroupId(Integer aAssetGroupId) {
		this.aAssetGroupId = aAssetGroupId;
	}

	@Basic
	@Column(name="A_ASSET_ID")
	public Integer getAAssetId() {
		return aAssetId;
	}

	public void setAAssetId(Integer aAssetId) {
		this.aAssetId = aAssetId;
	}

	@Basic
	@Column(name="A_CREATEASSET", length=1)
	public String getACreateasset() {
		return aCreateasset;
	}

	public void setACreateasset(String aCreateasset) {
		this.aCreateasset = aCreateasset;
	}

	@Basic
	@Column(name="A_PROCESSED", length=1)
	public String getAProcessed() {
		return aProcessed;
	}

	public void setAProcessed(String aProcessed) {
		this.aProcessed = aProcessed;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", nullable=false)
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name="AD_ORG_ID", nullable=false)
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getAmtacctcr() {
		return amtacctcr;
	}

	public void setAmtacctcr(BigDecimal amtacctcr) {
		this.amtacctcr = amtacctcr;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getAmtacctdr() {
		return amtacctdr;
	}

	public void setAmtacctdr(BigDecimal amtacctdr) {
		this.amtacctdr = amtacctdr;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getAmtsourcecr() {
		return amtsourcecr;
	}

	public void setAmtsourcecr(BigDecimal amtsourcecr) {
		this.amtsourcecr = amtsourcecr;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getAmtsourcedr() {
		return amtsourcedr;
	}

	public void setAmtsourcedr(BigDecimal amtsourcedr) {
		this.amtsourcedr = amtsourcedr;
	}

	@Basic
	@Column(name="C_CONVERSIONTYPE_ID", nullable=false)
	public Integer getCConversiontypeId() {
		return cConversiontypeId;
	}

	public void setCConversiontypeId(Integer cConversiontypeId) {
		this.cConversiontypeId = cConversiontypeId;
	}

	@Basic
	@Column(name="C_CURRENCY_ID", nullable=false)
	public Integer getCCurrencyId() {
		return cCurrencyId;
	}

	public void setCCurrencyId(Integer cCurrencyId) {
		this.cCurrencyId = cCurrencyId;
	}

	@Basic
	@Column(name="C_UOM_ID")
	public Integer getCUomId() {
		return cUomId;
	}

	public void setCUomId(Integer cUomId) {
		this.cUomId = cUomId;
	}

	@Basic
	@Column(name="C_VALIDCOMBINATION_ID", nullable=false)
	public Integer getCValidcombinationId() {
		return cValidcombinationId;
	}

	public void setCValidcombinationId(Integer cValidcombinationId) {
		this.cValidcombinationId = cValidcombinationId;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getCurrencyrate() {
		return currencyrate;
	}

	public void setCurrencyrate(BigDecimal currencyrate) {
		this.currencyrate = currencyrate;
	}

	@Basic
	@Column(nullable=false)
	public String getDateacct() {
		return dateacct;
	}

	public void setDateacct(String dateacct) {
		this.dateacct = dateacct;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(name="GL_JOURNAL_ID", nullable=false)
	public Integer getGlJournalId() {
		return glJournalId;
	}

	public void setGlJournalId(Integer glJournalId) {
		this.glJournalId = glJournalId;
	}

	@Id
	@Column(name="GL_JOURNALLINE_ID")
	public Integer getGlJournallineId() {
		return glJournallineId;
	}

	public void setGlJournallineId(Integer glJournallineId) {
		this.glJournallineId = glJournallineId;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getIsactive() {
		return isactive;
	}

	public void setIsactive(String isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getIsgenerated() {
		return isgenerated;
	}

	public void setIsgenerated(String isgenerated) {
		this.isgenerated = isgenerated;
	}

	@Basic
	@Column(nullable=false)
	public Integer getLine() {
		return line;
	}

	public void setLine(Integer line) {
		this.line = line;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getProcessed() {
		return processed;
	}

	public void setProcessed(String processed) {
		this.processed = processed;
	}

	@Basic
	public BigDecimal getQty() {
		return qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(nullable=false)
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}