package org.adempiere.model;

import java.math.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="gl_journalbatch")
public class GlJournalbatch extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer adClientId;
	private Integer adOrgId;
	private Integer cCurrencyId;
	private Integer cDoctypeId;
	private Integer cPeriodId;
	private BigDecimal controlamt;
	private String copyfrom;
	private String created;
	private Integer createdby;
	private String dateacct;
	private String datedoc;
	private String description;
	private String docaction;
	private String docstatus;
	private String documentno;
	private Integer glCategoryId;
	private Integer glJournalbatchId;
	private String isactive;
	private String isapproved;
	private String postingtype;
	private String processed;
	private String processing;
	private Integer reversalId;
	private BigDecimal totalcr;
	private BigDecimal totaldr;
	private String updated;
	private Integer updatedby;

	public GlJournalbatch() {
	}

	public GlJournalbatch(Integer glJournalbatchId) {
		this.glJournalbatchId = glJournalbatchId;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", nullable=false)
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name="AD_ORG_ID", nullable=false)
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Basic
	@Column(name="C_CURRENCY_ID")
	public Integer getCCurrencyId() {
		return cCurrencyId;
	}

	public void setCCurrencyId(Integer cCurrencyId) {
		this.cCurrencyId = cCurrencyId;
	}

	@Basic
	@Column(name="C_DOCTYPE_ID", nullable=false)
	public Integer getCDoctypeId() {
		return cDoctypeId;
	}

	public void setCDoctypeId(Integer cDoctypeId) {
		this.cDoctypeId = cDoctypeId;
	}

	@Basic
	@Column(name="C_PERIOD_ID")
	public Integer getCPeriodId() {
		return cPeriodId;
	}

	public void setCPeriodId(Integer cPeriodId) {
		this.cPeriodId = cPeriodId;
	}

	@Basic
	public BigDecimal getControlamt() {
		return controlamt;
	}

	public void setControlamt(BigDecimal controlamt) {
		this.controlamt = controlamt;
	}

	@Basic
	@Column(length=1)
	public String getCopyfrom() {
		return copyfrom;
	}

	public void setCopyfrom(String copyfrom) {
		this.copyfrom = copyfrom;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	public String getDateacct() {
		return dateacct;
	}

	public void setDateacct(String dateacct) {
		this.dateacct = dateacct;
	}

	@Basic
	public String getDatedoc() {
		return datedoc;
	}

	public void setDatedoc(String datedoc) {
		this.datedoc = datedoc;
	}

	@Basic
	@Column(nullable=false)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(nullable=false, length=2)
	public String getDocaction() {
		return docaction;
	}

	public void setDocaction(String docaction) {
		this.docaction = docaction;
	}

	@Basic
	@Column(nullable=false, length=2)
	public String getDocstatus() {
		return docstatus;
	}

	public void setDocstatus(String docstatus) {
		this.docstatus = docstatus;
	}

	@Basic
	@Column(nullable=false, length=30)
	public String getDocumentno() {
		return documentno;
	}

	public void setDocumentno(String documentno) {
		this.documentno = documentno;
	}

	@Basic
	@Column(name="GL_CATEGORY_ID")
	public Integer getGlCategoryId() {
		return glCategoryId;
	}

	public void setGlCategoryId(Integer glCategoryId) {
		this.glCategoryId = glCategoryId;
	}

	@Id
	@Column(name="GL_JOURNALBATCH_ID")
	public Integer getGlJournalbatchId() {
		return glJournalbatchId;
	}

	public void setGlJournalbatchId(Integer glJournalbatchId) {
		this.glJournalbatchId = glJournalbatchId;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getIsactive() {
		return isactive;
	}

	public void setIsactive(String isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(length=1)
	public String getIsapproved() {
		return isapproved;
	}

	public void setIsapproved(String isapproved) {
		this.isapproved = isapproved;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getPostingtype() {
		return postingtype;
	}

	public void setPostingtype(String postingtype) {
		this.postingtype = postingtype;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getProcessed() {
		return processed;
	}

	public void setProcessed(String processed) {
		this.processed = processed;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getProcessing() {
		return processing;
	}

	public void setProcessing(String processing) {
		this.processing = processing;
	}

	@Basic
	@Column(name="REVERSAL_ID")
	public Integer getReversalId() {
		return reversalId;
	}

	public void setReversalId(Integer reversalId) {
		this.reversalId = reversalId;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getTotalcr() {
		return totalcr;
	}

	public void setTotalcr(BigDecimal totalcr) {
		this.totalcr = totalcr;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getTotaldr() {
		return totaldr;
	}

	public void setTotaldr(BigDecimal totaldr) {
		this.totaldr = totaldr;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(nullable=false)
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}