package org.adempiere.model;

import java.math.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="i_invoice")
public class IInvoice extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private Integer aDOrgID;
	private Integer aDOrgTrxID;
	private Integer aDUserID;
	private Boolean active;
	private String activityValue;
	private String address1;
	private String address2;
	private String bPartnerValue;
	private Integer cActivityID;
	private Integer cBPartnerID;
	private Integer cBPartnerLocationID;
	private Integer cCampaignID;
	private Integer cChargeID;
	private Integer cCountryID;
	private Integer cCurrencyID;
	private Integer cDocTypeID;
	private Integer cInvoiceID;
	private Integer cInvoiceLineID;
	private Integer cLocationID;
	private Integer cPaymentTermID;
	private Integer cProjectID;
	private Integer cRegionID;
	private Integer cTaxID;
	private String chargeName;
	private String city;
	private String contactName;
	private Boolean countryCode;
	private String created;
	private Integer createdBy;
	private String dateAcct;
	private String dateInvoiced;
	private String description;
	private String docTypeName;
	private String documentNo;
	private String eMail;
	private String iErrorMsg;
	private Integer iInvoiceID;
	private Boolean iIsImported;
	private String lineDescription;
	private Integer mPriceListID;
	private Integer mProductID;
	private String name;
	private String paymentTermValue;
	private String phone;
	private String postal;
	private BigDecimal priceActual;
	private Boolean processed;
	private Boolean processing;
	private String productValue;
	private String projectValue;
	private BigDecimal qtyOrdered;
	private String regionName;
	private String sKU;
	private Boolean sOTrx;
	private Integer salesRepID;
	private BigDecimal taxAmt;
	private String taxIndicator;
	private String uPC;
	private String updated;
	private Integer updatedBy;

	public IInvoice() {
	}

	public IInvoice(Integer iInvoiceID) {
		this.iInvoiceID = iInvoiceID;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT")
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT")
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Basic
	@Column(name="AD_ORGTRX_ID", columnDefinition="INT")
	public Integer getADOrgTrxID() {
		return aDOrgTrxID;
	}

	public void setADOrgTrxID(Integer aDOrgTrxID) {
		this.aDOrgTrxID = aDOrgTrxID;
	}

	@Basic
	@Column(name="AD_USER_ID", columnDefinition="INT")
	public Integer getADUserID() {
		return aDUserID;
	}

	public void setADUserID(Integer aDUserID) {
		this.aDUserID = aDUserID;
	}

	@Basic
	@Column(name="ISACTIVE")
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(length=40)
	public String getActivityValue() {
		return activityValue;
	}

	public void setActivityValue(String activityValue) {
		this.activityValue = activityValue;
	}

	@Basic
	@Column(length=60)
	public String getAddress1() {
		return address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Basic
	@Column(length=60)
	public String getAddress2() {
		return address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Basic
	@Column(length=40)
	public String getBPartnerValue() {
		return bPartnerValue;
	}

	public void setBPartnerValue(String bPartnerValue) {
		this.bPartnerValue = bPartnerValue;
	}

	@Basic
	@Column(name="C_ACTIVITY_ID", columnDefinition="INT")
	public Integer getCActivityID() {
		return cActivityID;
	}

	public void setCActivityID(Integer cActivityID) {
		this.cActivityID = cActivityID;
	}

	@Basic
	@Column(name="C_BPARTNER_ID", columnDefinition="INT")
	public Integer getCBPartnerID() {
		return cBPartnerID;
	}

	public void setCBPartnerID(Integer cBPartnerID) {
		this.cBPartnerID = cBPartnerID;
	}

	@Basic
	@Column(name="C_BPARTNER_LOCATION_ID", columnDefinition="INT")
	public Integer getCBPartnerLocationID() {
		return cBPartnerLocationID;
	}

	public void setCBPartnerLocationID(Integer cBPartnerLocationID) {
		this.cBPartnerLocationID = cBPartnerLocationID;
	}

	@Basic
	@Column(name="C_CAMPAIGN_ID", columnDefinition="INT")
	public Integer getCCampaignID() {
		return cCampaignID;
	}

	public void setCCampaignID(Integer cCampaignID) {
		this.cCampaignID = cCampaignID;
	}

	@Basic
	@Column(name="C_CHARGE_ID", columnDefinition="INT")
	public Integer getCChargeID() {
		return cChargeID;
	}

	public void setCChargeID(Integer cChargeID) {
		this.cChargeID = cChargeID;
	}

	@Basic
	@Column(name="C_COUNTRY_ID", columnDefinition="INT")
	public Integer getCCountryID() {
		return cCountryID;
	}

	public void setCCountryID(Integer cCountryID) {
		this.cCountryID = cCountryID;
	}

	@Basic
	@Column(name="C_CURRENCY_ID", columnDefinition="INT")
	public Integer getCCurrencyID() {
		return cCurrencyID;
	}

	public void setCCurrencyID(Integer cCurrencyID) {
		this.cCurrencyID = cCurrencyID;
	}

	@Basic
	@Column(name="C_DOCTYPE_ID", columnDefinition="INT")
	public Integer getCDocTypeID() {
		return cDocTypeID;
	}

	public void setCDocTypeID(Integer cDocTypeID) {
		this.cDocTypeID = cDocTypeID;
	}

	@Basic
	@Column(name="C_INVOICE_ID", columnDefinition="INT")
	public Integer getCInvoiceID() {
		return cInvoiceID;
	}

	public void setCInvoiceID(Integer cInvoiceID) {
		this.cInvoiceID = cInvoiceID;
	}

	@Basic
	@Column(name="C_INVOICELINE_ID", columnDefinition="INT")
	public Integer getCInvoiceLineID() {
		return cInvoiceLineID;
	}

	public void setCInvoiceLineID(Integer cInvoiceLineID) {
		this.cInvoiceLineID = cInvoiceLineID;
	}

	@Basic
	@Column(name="C_LOCATION_ID", columnDefinition="INT")
	public Integer getCLocationID() {
		return cLocationID;
	}

	public void setCLocationID(Integer cLocationID) {
		this.cLocationID = cLocationID;
	}

	@Basic
	@Column(name="C_PAYMENTTERM_ID", columnDefinition="INT")
	public Integer getCPaymentTermID() {
		return cPaymentTermID;
	}

	public void setCPaymentTermID(Integer cPaymentTermID) {
		this.cPaymentTermID = cPaymentTermID;
	}

	@Basic
	@Column(name="C_PROJECT_ID", columnDefinition="INT")
	public Integer getCProjectID() {
		return cProjectID;
	}

	public void setCProjectID(Integer cProjectID) {
		this.cProjectID = cProjectID;
	}

	@Basic
	@Column(name="C_REGION_ID", columnDefinition="INT")
	public Integer getCRegionID() {
		return cRegionID;
	}

	public void setCRegionID(Integer cRegionID) {
		this.cRegionID = cRegionID;
	}

	@Basic
	@Column(name="C_TAX_ID", columnDefinition="INT")
	public Integer getCTaxID() {
		return cTaxID;
	}

	public void setCTaxID(Integer cTaxID) {
		this.cTaxID = cTaxID;
	}

	@Basic
	@Column(length=60)
	public String getChargeName() {
		return chargeName;
	}

	public void setChargeName(String chargeName) {
		this.chargeName = chargeName;
	}

	@Basic
	@Column(length=60)
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Basic
	@Column(length=60)
	public String getContactName() {
		return contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	@Basic
	public Boolean isCountryCode() {
		return countryCode;
	}

	public void setCountryCode(Boolean countryCode) {
		this.countryCode = countryCode;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	public String getDateAcct() {
		return dateAcct;
	}

	public void setDateAcct(String dateAcct) {
		this.dateAcct = dateAcct;
	}

	@Basic
	public String getDateInvoiced() {
		return dateInvoiced;
	}

	public void setDateInvoiced(String dateInvoiced) {
		this.dateInvoiced = dateInvoiced;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(length=60)
	public String getDocTypeName() {
		return docTypeName;
	}

	public void setDocTypeName(String docTypeName) {
		this.docTypeName = docTypeName;
	}

	@Basic
	@Column(length=30)
	public String getDocumentNo() {
		return documentNo;
	}

	public void setDocumentNo(String documentNo) {
		this.documentNo = documentNo;
	}

	@Basic
	@Column(length=60)
	public String getEMail() {
		return eMail;
	}

	public void setEMail(String eMail) {
		this.eMail = eMail;
	}

	@Basic
	@Column(name="I_ERRORMSG", length=2000)
	public String getIErrorMsg() {
		return iErrorMsg;
	}

	public void setIErrorMsg(String iErrorMsg) {
		this.iErrorMsg = iErrorMsg;
	}

	@Id
	@Column(name="I_INVOICE_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_753", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "I_Invoice", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_753")
	public Integer getIInvoiceID() {
		return iInvoiceID;
	}

	public void setIInvoiceID(Integer iInvoiceID) {
		this.iInvoiceID = iInvoiceID;
	}

	@Basic
	@Column(name="I_ISIMPORTED", nullable=false)
	public Boolean isIIsImported() {
		return iIsImported;
	}

	public void setIIsImported(Boolean iIsImported) {
		this.iIsImported = iIsImported;
	}

	@Basic
	public String getLineDescription() {
		return lineDescription;
	}

	public void setLineDescription(String lineDescription) {
		this.lineDescription = lineDescription;
	}

	@Basic
	@Column(name="M_PRICELIST_ID", columnDefinition="INT")
	public Integer getMPriceListID() {
		return mPriceListID;
	}

	public void setMPriceListID(Integer mPriceListID) {
		this.mPriceListID = mPriceListID;
	}

	@Basic
	@Column(name="M_PRODUCT_ID", columnDefinition="INT")
	public Integer getMProductID() {
		return mProductID;
	}

	public void setMProductID(Integer mProductID) {
		this.mProductID = mProductID;
	}

	@Basic
	@Column(length=60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	@Column(length=40)
	public String getPaymentTermValue() {
		return paymentTermValue;
	}

	public void setPaymentTermValue(String paymentTermValue) {
		this.paymentTermValue = paymentTermValue;
	}

	@Basic
	@Column(length=40)
	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Basic
	@Column(length=10)
	public String getPostal() {
		return postal;
	}

	public void setPostal(String postal) {
		this.postal = postal;
	}

	@Basic
	public BigDecimal getPriceActual() {
		return priceActual;
	}

	public void setPriceActual(BigDecimal priceActual) {
		this.priceActual = priceActual;
	}

	@Basic
	public Boolean isProcessed() {
		return processed;
	}

	public void setProcessed(Boolean processed) {
		this.processed = processed;
	}

	@Basic
	public Boolean isProcessing() {
		return processing;
	}

	public void setProcessing(Boolean processing) {
		this.processing = processing;
	}

	@Basic
	@Column(length=40)
	public String getProductValue() {
		return productValue;
	}

	public void setProductValue(String productValue) {
		this.productValue = productValue;
	}

	@Basic
	@Column(length=40)
	public String getProjectValue() {
		return projectValue;
	}

	public void setProjectValue(String projectValue) {
		this.projectValue = projectValue;
	}

	@Basic
	public BigDecimal getQtyOrdered() {
		return qtyOrdered;
	}

	public void setQtyOrdered(BigDecimal qtyOrdered) {
		this.qtyOrdered = qtyOrdered;
	}

	@Basic
	@Column(length=60)
	public String getRegionName() {
		return regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}

	@Basic
	@Column(length=30)
	public String getSKU() {
		return sKU;
	}

	public void setSKU(String sKU) {
		this.sKU = sKU;
	}

	@Basic
	@Column(name="ISSOTRX")
	public Boolean isSOTrx() {
		return sOTrx;
	}

	public void setSOTrx(Boolean sOTrx) {
		this.sOTrx = sOTrx;
	}

	@Basic
	@Column(name="SALESREP_ID", columnDefinition="INT")
	public Integer getSalesRepID() {
		return salesRepID;
	}

	public void setSalesRepID(Integer salesRepID) {
		this.salesRepID = salesRepID;
	}

	@Basic
	public BigDecimal getTaxAmt() {
		return taxAmt;
	}

	public void setTaxAmt(BigDecimal taxAmt) {
		this.taxAmt = taxAmt;
	}

	@Basic
	@Column(length=10)
	public String getTaxIndicator() {
		return taxIndicator;
	}

	public void setTaxIndicator(String taxIndicator) {
		this.taxIndicator = taxIndicator;
	}

	@Basic
	@Column(length=30)
	public String getUPC() {
		return uPC;
	}

	public void setUPC(String uPC) {
		this.uPC = uPC;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}
}