package org.adempiere.model;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: org.adempiere.model.KEntryRelated
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class KEntryRelatedPK implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("org.adempiere.model.KEntryRelated"); }
		catch(Exception e) {}
	}

	public Integer kEntryID;
	public Integer kEntryRelatedID;

	public KEntryRelatedPK() {
	}

	public KEntryRelatedPK(String str) {
		fromString(str);
	}

	public Integer getKEntryID() {
		return kEntryID;
	}

	public void setKEntryID(Integer kEntryID) {
		this.kEntryID = kEntryID;
	}

	public Integer getKEntryRelatedID() {
		return kEntryRelatedID;
	}

	public void setKEntryRelatedID(Integer kEntryRelatedID) {
		this.kEntryRelatedID = kEntryRelatedID;
	}

	public String toString() {
		return String.valueOf(kEntryID)
			+ "::" + String.valueOf(kEntryRelatedID);
	}

	public int hashCode() {
		int rs = 17;
		rs = rs * 37 + ((kEntryID == null) ? 0 : kEntryID.hashCode());
		rs = rs * 37 + ((kEntryRelatedID == null) ? 0 : kEntryRelatedID.hashCode());
		return rs;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		KEntryRelatedPK other = (KEntryRelatedPK) obj;
		return ((kEntryID == null && other.kEntryID == null)
			|| (kEntryID != null && kEntryID.equals(other.kEntryID)))
			&& ((kEntryRelatedID == null && other.kEntryRelatedID == null)
			|| (kEntryRelatedID != null && kEntryRelatedID.equals(other.kEntryRelatedID)));
	}

	private void fromString(String str) {
		Tokenizer toke = new Tokenizer(str);
		str = toke.nextToken();
		if("null".equals(str))
			kEntryID = null;
		else
			kEntryID = new Integer(str);
		str = toke.nextToken();
		if("null".equals(str))
			kEntryRelatedID = null;
		else
			kEntryRelatedID = new Integer(str);
	}

	protected static class Tokenizer {
		private final String str;
		private int last;

		public Tokenizer (String str) {
			this.str = str;
		}

		public String nextToken () {
			int next = str.indexOf("::", last);
			String part;
			if(next == -1) {
				part = str.substring(last);
				last = str.length();
			} else {
				part = str.substring(last, next);
				last = next + 2;
			}
			return part;
		}
	}
}