package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="m_attributeuse")
@IdClass(org.adempiere.model.MAttributeUsePK.class)
public class MAttributeUse extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private Integer aDOrgID;
	private Boolean active;
	private String created;
	private Integer createdBy;
	private Integer mAttributeID;
	private Integer mAttributeSetID;
	private Integer seqNo;
	private String updated;
	private Integer updatedBy;

	public MAttributeUse() {
	}

	public MAttributeUse(Integer mAttributeID, Integer mAttributeSetID) {
		this.mAttributeID = mAttributeID;
		this.mAttributeSetID = mAttributeSetID;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Basic
	@Column(name="ISACTIVE", nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Id
	@Column(name="M_ATTRIBUTE_ID", columnDefinition="INT")
	public Integer getMAttributeID() {
		return mAttributeID;
	}

	public void setMAttributeID(Integer mAttributeID) {
		this.mAttributeID = mAttributeID;
	}

	@Id
	@Column(name="M_ATTRIBUTESET_ID", columnDefinition="INT")
	public Integer getMAttributeSetID() {
		return mAttributeSetID;
	}

	public void setMAttributeSetID(Integer mAttributeSetID) {
		this.mAttributeSetID = mAttributeSetID;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getSeqNo() {
		return seqNo;
	}

	public void setSeqNo(Integer seqNo) {
		this.seqNo = seqNo;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}
}