package org.adempiere.model;

import java.math.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="m_freight")
public class MFreight extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private Integer aDOrgID;
	private Boolean active;
	private Integer cCountryID;
	private Integer cCurrencyID;
	private Integer cRegionID;
	private String created;
	private Integer createdBy;
	private BigDecimal freightAmt;
	private Integer mFreightCategoryID;
	private Integer mFreightID;
	private Integer mShipperID;
	private Integer toCountryID;
	private Integer toRegionID;
	private String updated;
	private Integer updatedBy;
	private String validFrom;

	public MFreight() {
	}

	public MFreight(Integer mFreightID) {
		this.mFreightID = mFreightID;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Basic
	@Column(name="ISACTIVE", nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(name="C_COUNTRY_ID", columnDefinition="INT")
	public Integer getCCountryID() {
		return cCountryID;
	}

	public void setCCountryID(Integer cCountryID) {
		this.cCountryID = cCountryID;
	}

	@Basic
	@Column(name="C_CURRENCY_ID", columnDefinition="INT", nullable=false)
	public Integer getCCurrencyID() {
		return cCurrencyID;
	}

	public void setCCurrencyID(Integer cCurrencyID) {
		this.cCurrencyID = cCurrencyID;
	}

	@Basic
	@Column(name="C_REGION_ID", columnDefinition="INT")
	public Integer getCRegionID() {
		return cRegionID;
	}

	public void setCRegionID(Integer cRegionID) {
		this.cRegionID = cRegionID;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getFreightAmt() {
		return freightAmt;
	}

	public void setFreightAmt(BigDecimal freightAmt) {
		this.freightAmt = freightAmt;
	}

	@Basic
	@Column(name="M_FREIGHTCATEGORY_ID", columnDefinition="INT", nullable=false)
	public Integer getMFreightCategoryID() {
		return mFreightCategoryID;
	}

	public void setMFreightCategoryID(Integer mFreightCategoryID) {
		this.mFreightCategoryID = mFreightCategoryID;
	}

	@Id
	@Column(name="M_FREIGHT_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_751", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "M_Freight", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_751")
	public Integer getMFreightID() {
		return mFreightID;
	}

	public void setMFreightID(Integer mFreightID) {
		this.mFreightID = mFreightID;
	}

	@Basic
	@Column(name="M_SHIPPER_ID", columnDefinition="INT", nullable=false)
	public Integer getMShipperID() {
		return mShipperID;
	}

	public void setMShipperID(Integer mShipperID) {
		this.mShipperID = mShipperID;
	}

	@Basic
	@Column(name="TO_COUNTRY_ID", columnDefinition="INT")
	public Integer getToCountryID() {
		return toCountryID;
	}

	public void setToCountryID(Integer toCountryID) {
		this.toCountryID = toCountryID;
	}

	@Basic
	@Column(name="TO_REGION_ID", columnDefinition="INT")
	public Integer getToRegionID() {
		return toRegionID;
	}

	public void setToRegionID(Integer toRegionID) {
		this.toRegionID = toRegionID;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Basic
	@Column(nullable=false)
	public String getValidFrom() {
		return validFrom;
	}

	public void setValidFrom(String validFrom) {
		this.validFrom = validFrom;
	}
}