package org.adempiere.model;

import java.math.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="m_inoutconfirm")
public class MInOutConfirm extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private Integer aDOrgID;
	private Boolean active;
	private BigDecimal approvalAmt;
	private Boolean approved;
	private Integer cInvoiceID;
	private Boolean cancelled;
	private String confirmType;
	private String confirmationNo;
	private Boolean createPackage;
	private String created;
	private Integer createdBy;
	private String description;
	private String docAction;
	private String docStatus;
	private String documentNo;
	private Boolean inDispute;
	private Integer mInOutConfirmID;
	private Integer mInOutID;
	private Integer mInventoryID;
	private Boolean processed;
	private Boolean processing;
	private String updated;
	private Integer updatedBy;

	public MInOutConfirm() {
	}

	public MInOutConfirm(Integer mInOutConfirmID) {
		this.mInOutConfirmID = mInOutConfirmID;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Basic
	@Column(name="ISACTIVE", nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	public BigDecimal getApprovalAmt() {
		return approvalAmt;
	}

	public void setApprovalAmt(BigDecimal approvalAmt) {
		this.approvalAmt = approvalAmt;
	}

	@Basic
	@Column(name="ISAPPROVED", nullable=false)
	public Boolean isApproved() {
		return approved;
	}

	public void setApproved(Boolean approved) {
		this.approved = approved;
	}

	@Basic
	@Column(name="C_INVOICE_ID", columnDefinition="INT")
	public Integer getCInvoiceID() {
		return cInvoiceID;
	}

	public void setCInvoiceID(Integer cInvoiceID) {
		this.cInvoiceID = cInvoiceID;
	}

	@Basic
	@Column(name="ISCANCELLED", nullable=false)
	public Boolean isCancelled() {
		return cancelled;
	}

	public void setCancelled(Boolean cancelled) {
		this.cancelled = cancelled;
	}

	@Basic
	@Column(nullable=false, length=2)
	public String getConfirmType() {
		return confirmType;
	}

	public void setConfirmType(String confirmType) {
		this.confirmType = confirmType;
	}

	@Basic
	@Column(length=20)
	public String getConfirmationNo() {
		return confirmationNo;
	}

	public void setConfirmationNo(String confirmationNo) {
		this.confirmationNo = confirmationNo;
	}

	@Basic
	public Boolean isCreatePackage() {
		return createPackage;
	}

	public void setCreatePackage(Boolean createPackage) {
		this.createPackage = createPackage;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(nullable=false, length=2)
	public String getDocAction() {
		return docAction;
	}

	public void setDocAction(String docAction) {
		this.docAction = docAction;
	}

	@Basic
	@Column(nullable=false, length=2)
	public String getDocStatus() {
		return docStatus;
	}

	public void setDocStatus(String docStatus) {
		this.docStatus = docStatus;
	}

	@Basic
	@Column(nullable=false, length=30)
	public String getDocumentNo() {
		return documentNo;
	}

	public void setDocumentNo(String documentNo) {
		this.documentNo = documentNo;
	}

	@Basic
	@Column(name="ISINDISPUTE", nullable=false)
	public Boolean isInDispute() {
		return inDispute;
	}

	public void setInDispute(Boolean inDispute) {
		this.inDispute = inDispute;
	}

	@Id
	@Column(name="M_INOUTCONFIRM_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_954", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "M_InOutConfirm", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_954")
	public Integer getMInOutConfirmID() {
		return mInOutConfirmID;
	}

	public void setMInOutConfirmID(Integer mInOutConfirmID) {
		this.mInOutConfirmID = mInOutConfirmID;
	}

	@Basic
	@Column(name="M_INOUT_ID", columnDefinition="INT", nullable=false)
	public Integer getMInOutID() {
		return mInOutID;
	}

	public void setMInOutID(Integer mInOutID) {
		this.mInOutID = mInOutID;
	}

	@Basic
	@Column(name="M_INVENTORY_ID", columnDefinition="INT")
	public Integer getMInventoryID() {
		return mInventoryID;
	}

	public void setMInventoryID(Integer mInventoryID) {
		this.mInventoryID = mInventoryID;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isProcessed() {
		return processed;
	}

	public void setProcessed(Boolean processed) {
		this.processed = processed;
	}

	@Basic
	public Boolean isProcessing() {
		return processing;
	}

	public void setProcessing(Boolean processing) {
		this.processing = processing;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}
}