package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="m_pricelist_version")
public class MPriceListVersion extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private Integer aDOrgID;
	private Boolean active;
	private String created;
	private Integer createdBy;
	private String description;
	private Integer mDiscountSchemaID;
	private Integer mPriceListID;
	private Integer mPriceListVersionID;
	private Integer mPricelistVersionBaseID;
	private String name;
	private Boolean procCreate;
	private String updated;
	private Integer updatedBy;
	private String validFrom;

	public MPriceListVersion() {
	}

	public MPriceListVersion(Integer mPriceListVersionID) {
		this.mPriceListVersionID = mPriceListVersionID;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Basic
	@Column(name="ISACTIVE", nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(name="M_DISCOUNTSCHEMA_ID", columnDefinition="INT", nullable=false)
	public Integer getMDiscountSchemaID() {
		return mDiscountSchemaID;
	}

	public void setMDiscountSchemaID(Integer mDiscountSchemaID) {
		this.mDiscountSchemaID = mDiscountSchemaID;
	}

	@Basic
	@Column(name="M_PRICELIST_ID", columnDefinition="INT", nullable=false)
	public Integer getMPriceListID() {
		return mPriceListID;
	}

	public void setMPriceListID(Integer mPriceListID) {
		this.mPriceListID = mPriceListID;
	}

	@Id
	@Column(name="M_PRICELIST_VERSION_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_210", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "M_PriceList_Version", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_210")
	public Integer getMPriceListVersionID() {
		return mPriceListVersionID;
	}

	public void setMPriceListVersionID(Integer mPriceListVersionID) {
		this.mPriceListVersionID = mPriceListVersionID;
	}

	@Basic
	@Column(name="M_PRICELIST_VERSION_BASE_ID", columnDefinition="INT")
	public Integer getMPricelistVersionBaseID() {
		return mPricelistVersionBaseID;
	}

	public void setMPricelistVersionBaseID(Integer mPricelistVersionBaseID) {
		this.mPricelistVersionBaseID = mPricelistVersionBaseID;
	}

	@Basic
	@Column(nullable=false, length=60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	public Boolean isProcCreate() {
		return procCreate;
	}

	public void setProcCreate(Boolean procCreate) {
		this.procCreate = procCreate;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Basic
	@Column(nullable=false)
	public String getValidFrom() {
		return validFrom;
	}

	public void setValidFrom(String validFrom) {
		this.validFrom = validFrom;
	}
}