package org.adempiere.model;

import java.math.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="m_productoperation")
public class MProductOperation extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private Integer aDOrgID;
	private Boolean active;
	private String created;
	private Integer createdBy;
	private String description;
	private String help;
	private Integer mProductID;
	private Integer mProductOperationID;
	private String name;
	private BigDecimal setupTime;
	private BigDecimal teardownTime;
	private BigDecimal unitRuntime;
	private String updated;
	private Integer updatedBy;

	public MProductOperation() {
	}

	public MProductOperation(Integer mProductOperationID) {
		this.mProductOperationID = mProductOperationID;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Basic
	@Column(name="ISACTIVE", nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(length=2000)
	public String getHelp() {
		return help;
	}

	public void setHelp(String help) {
		this.help = help;
	}

	@Basic
	@Column(name="M_PRODUCT_ID", columnDefinition="INT", nullable=false)
	public Integer getMProductID() {
		return mProductID;
	}

	public void setMProductID(Integer mProductID) {
		this.mProductID = mProductID;
	}

	@Id
	@Column(name="M_PRODUCTOPERATION_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_1132", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "M_ProductOperation", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_1132")
	public Integer getMProductOperationID() {
		return mProductOperationID;
	}

	public void setMProductOperationID(Integer mProductOperationID) {
		this.mProductOperationID = mProductOperationID;
	}

	@Basic
	@Column(nullable=false, length=60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	public BigDecimal getSetupTime() {
		return setupTime;
	}

	public void setSetupTime(BigDecimal setupTime) {
		this.setupTime = setupTime;
	}

	@Basic
	public BigDecimal getTeardownTime() {
		return teardownTime;
	}

	public void setTeardownTime(BigDecimal teardownTime) {
		this.teardownTime = teardownTime;
	}

	@Basic
	public BigDecimal getUnitRuntime() {
		return unitRuntime;
	}

	public void setUnitRuntime(BigDecimal unitRuntime) {
		this.unitRuntime = unitRuntime;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}
}