package org.adempiere.model;

import java.math.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="m_replenish")
@IdClass(org.adempiere.model.MReplenishPK.class)
public class MReplenish extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private Integer aDOrgID;
	private Boolean active;
	private String created;
	private Integer createdBy;
	private BigDecimal levelMax;
	private BigDecimal levelMin;
	private Integer mLocatorID;
	private Integer mProductID;
	private Integer mWarehouseID;
	private Integer mWarehouseSourceID;
	private String replenishType;
	private String updated;
	private Integer updatedBy;

	public MReplenish() {
	}

	public MReplenish(Integer mProductID, Integer mWarehouseID) {
		this.mProductID = mProductID;
		this.mWarehouseID = mWarehouseID;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Basic
	@Column(name="ISACTIVE", nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	@Column(name="LEVEL_MAX", nullable=false)
	public BigDecimal getLevelMax() {
		return levelMax;
	}

	public void setLevelMax(BigDecimal levelMax) {
		this.levelMax = levelMax;
	}

	@Basic
	@Column(name="LEVEL_MIN", nullable=false)
	public BigDecimal getLevelMin() {
		return levelMin;
	}

	public void setLevelMin(BigDecimal levelMin) {
		this.levelMin = levelMin;
	}

	@Basic
	@Column(name="M_LOCATOR_ID", columnDefinition="INT")
	public Integer getMLocatorID() {
		return mLocatorID;
	}

	public void setMLocatorID(Integer mLocatorID) {
		this.mLocatorID = mLocatorID;
	}

	@Id
	@Column(name="M_PRODUCT_ID", columnDefinition="INT")
	public Integer getMProductID() {
		return mProductID;
	}

	public void setMProductID(Integer mProductID) {
		this.mProductID = mProductID;
	}

	@Id
	@Column(name="M_WAREHOUSE_ID", columnDefinition="INT")
	public Integer getMWarehouseID() {
		return mWarehouseID;
	}

	public void setMWarehouseID(Integer mWarehouseID) {
		this.mWarehouseID = mWarehouseID;
	}

	@Basic
	@Column(name="M_WAREHOUSESOURCE_ID", columnDefinition="INT")
	public Integer getMWarehouseSourceID() {
		return mWarehouseSourceID;
	}

	public void setMWarehouseSourceID(Integer mWarehouseSourceID) {
		this.mWarehouseSourceID = mWarehouseSourceID;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getReplenishType() {
		return replenishType;
	}

	public void setReplenishType(String replenishType) {
		this.replenishType = replenishType;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}
}