package org.adempiere.model;

import java.math.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="pp_order_bomline")
public class PPOrderBOMLine extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aDClientID;
	private Integer aDOrgID;
	private Integer aDUserID;
	private Boolean active;
	private BigDecimal assay;
	private String backflushGroup;
	private Integer cUOMID;
	private String componentType;
	private BigDecimal costAllocationPerc;
	private String created;
	private Integer createdBy;
	private Boolean critical;
	private String dateDelivered;
	private String description;
	private String feature;
	private BigDecimal forecast;
	private String help;
	private Integer leadTimeOffset;
	private Integer line;
	private Integer mAttributeSetInstanceID;
	private Integer mChangeNoticeID;
	private Integer mLocatorID;
	private Integer mProductID;
	private Integer mWarehouseID;
	private Integer pPOrderBOMID;
	private Integer pPOrderBOMLineID;
	private Integer pPOrderID;
	private BigDecimal qtyBOM;
	private BigDecimal qtyBatch;
	private BigDecimal qtyDelivered;
	private BigDecimal qtyEntered;
	private Boolean qtyPercentage;
	private BigDecimal qtyPost;
	private BigDecimal qtyReject;
	private BigDecimal qtyRequiered;
	private BigDecimal qtyReserved;
	private BigDecimal qtyScrap;
	private BigDecimal scrap;
	private String sueMethod;
	private String updated;
	private Integer updatedBy;
	private String validFrom;
	private String validTo;

	public PPOrderBOMLine() {
	}

	public PPOrderBOMLine(Integer pPOrderBOMLineID) {
		this.pPOrderBOMLineID = pPOrderBOMLineID;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Basic
	@Column(name="AD_USER_ID", columnDefinition="INT")
	public Integer getADUserID() {
		return aDUserID;
	}

	public void setADUserID(Integer aDUserID) {
		this.aDUserID = aDUserID;
	}

	@Basic
	@Column(name="ISACTIVE", nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	public BigDecimal getAssay() {
		return assay;
	}

	public void setAssay(BigDecimal assay) {
		this.assay = assay;
	}

	@Basic
	@Column(length=30)
	public String getBackflushGroup() {
		return backflushGroup;
	}

	public void setBackflushGroup(String backflushGroup) {
		this.backflushGroup = backflushGroup;
	}

	@Basic
	@Column(name="C_UOM_ID", columnDefinition="INT", nullable=false)
	public Integer getCUOMID() {
		return cUOMID;
	}

	public void setCUOMID(Integer cUOMID) {
		this.cUOMID = cUOMID;
	}

	@Basic
	@Column(length=2)
	public String getComponentType() {
		return componentType;
	}

	public void setComponentType(String componentType) {
		this.componentType = componentType;
	}

	@Basic
	public BigDecimal getCostAllocationPerc() {
		return costAllocationPerc;
	}

	public void setCostAllocationPerc(BigDecimal costAllocationPerc) {
		this.costAllocationPerc = costAllocationPerc;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	@Column(name="ISCRITICAL", nullable=false)
	public Boolean isCritical() {
		return critical;
	}

	public void setCritical(Boolean critical) {
		this.critical = critical;
	}

	@Basic
	public String getDateDelivered() {
		return dateDelivered;
	}

	public void setDateDelivered(String dateDelivered) {
		this.dateDelivered = dateDelivered;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(length=30)
	public String getFeature() {
		return feature;
	}

	public void setFeature(String feature) {
		this.feature = feature;
	}

	@Basic
	public BigDecimal getForecast() {
		return forecast;
	}

	public void setForecast(BigDecimal forecast) {
		this.forecast = forecast;
	}

	@Basic
	@Column(length=2000)
	public String getHelp() {
		return help;
	}

	public void setHelp(String help) {
		this.help = help;
	}

	@Basic
	@Column(columnDefinition="INT")
	public Integer getLeadTimeOffset() {
		return leadTimeOffset;
	}

	public void setLeadTimeOffset(Integer leadTimeOffset) {
		this.leadTimeOffset = leadTimeOffset;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getLine() {
		return line;
	}

	public void setLine(Integer line) {
		this.line = line;
	}

	@Basic
	@Column(name="M_ATTRIBUTESETINSTANCE_ID", columnDefinition="INT")
	public Integer getMAttributeSetInstanceID() {
		return mAttributeSetInstanceID;
	}

	public void setMAttributeSetInstanceID(Integer mAttributeSetInstanceID) {
		this.mAttributeSetInstanceID = mAttributeSetInstanceID;
	}

	@Basic
	@Column(name="M_CHANGENOTICE_ID", columnDefinition="INT")
	public Integer getMChangeNoticeID() {
		return mChangeNoticeID;
	}

	public void setMChangeNoticeID(Integer mChangeNoticeID) {
		this.mChangeNoticeID = mChangeNoticeID;
	}

	@Basic
	@Column(name="M_LOCATOR_ID", columnDefinition="INT")
	public Integer getMLocatorID() {
		return mLocatorID;
	}

	public void setMLocatorID(Integer mLocatorID) {
		this.mLocatorID = mLocatorID;
	}

	@Basic
	@Column(name="M_PRODUCT_ID", columnDefinition="INT", nullable=false)
	public Integer getMProductID() {
		return mProductID;
	}

	public void setMProductID(Integer mProductID) {
		this.mProductID = mProductID;
	}

	@Basic
	@Column(name="M_WAREHOUSE_ID", columnDefinition="INT", nullable=false)
	public Integer getMWarehouseID() {
		return mWarehouseID;
	}

	public void setMWarehouseID(Integer mWarehouseID) {
		this.mWarehouseID = mWarehouseID;
	}

	@Basic
	@Column(name="PP_ORDER_BOM_ID", columnDefinition="INT", nullable=false)
	public Integer getPPOrderBOMID() {
		return pPOrderBOMID;
	}

	public void setPPOrderBOMID(Integer pPOrderBOMID) {
		this.pPOrderBOMID = pPOrderBOMID;
	}

	@Id
	@Column(name="PP_ORDER_BOMLINE_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_53022", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "PP_Order_BOMLine", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_53022")
	public Integer getPPOrderBOMLineID() {
		return pPOrderBOMLineID;
	}

	public void setPPOrderBOMLineID(Integer pPOrderBOMLineID) {
		this.pPOrderBOMLineID = pPOrderBOMLineID;
	}

	@Basic
	@Column(name="PP_ORDER_ID", columnDefinition="INT", nullable=false)
	public Integer getPPOrderID() {
		return pPOrderID;
	}

	public void setPPOrderID(Integer pPOrderID) {
		this.pPOrderID = pPOrderID;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getQtyBOM() {
		return qtyBOM;
	}

	public void setQtyBOM(BigDecimal qtyBOM) {
		this.qtyBOM = qtyBOM;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getQtyBatch() {
		return qtyBatch;
	}

	public void setQtyBatch(BigDecimal qtyBatch) {
		this.qtyBatch = qtyBatch;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getQtyDelivered() {
		return qtyDelivered;
	}

	public void setQtyDelivered(BigDecimal qtyDelivered) {
		this.qtyDelivered = qtyDelivered;
	}

	@Basic
	public BigDecimal getQtyEntered() {
		return qtyEntered;
	}

	public void setQtyEntered(BigDecimal qtyEntered) {
		this.qtyEntered = qtyEntered;
	}

	@Basic
	@Column(name="ISQTYPERCENTAGE")
	public Boolean isQtyPercentage() {
		return qtyPercentage;
	}

	public void setQtyPercentage(Boolean qtyPercentage) {
		this.qtyPercentage = qtyPercentage;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getQtyPost() {
		return qtyPost;
	}

	public void setQtyPost(BigDecimal qtyPost) {
		this.qtyPost = qtyPost;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getQtyReject() {
		return qtyReject;
	}

	public void setQtyReject(BigDecimal qtyReject) {
		this.qtyReject = qtyReject;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getQtyRequiered() {
		return qtyRequiered;
	}

	public void setQtyRequiered(BigDecimal qtyRequiered) {
		this.qtyRequiered = qtyRequiered;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getQtyReserved() {
		return qtyReserved;
	}

	public void setQtyReserved(BigDecimal qtyReserved) {
		this.qtyReserved = qtyReserved;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getQtyScrap() {
		return qtyScrap;
	}

	public void setQtyScrap(BigDecimal qtyScrap) {
		this.qtyScrap = qtyScrap;
	}

	@Basic
	public BigDecimal getScrap() {
		return scrap;
	}

	public void setScrap(BigDecimal scrap) {
		this.scrap = scrap;
	}

	@Basic
	@Column(name="ISSUEMETHOD", length=1)
	public String getSueMethod() {
		return sueMethod;
	}

	public void setSueMethod(String sueMethod) {
		this.sueMethod = sueMethod;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Basic
	@Column(nullable=false)
	public String getValidFrom() {
		return validFrom;
	}

	public void setValidFrom(String validFrom) {
		this.validFrom = validFrom;
	}

	@Basic
	public String getValidTo() {
		return validTo;
	}

	public void setValidTo(String validTo) {
		this.validTo = validTo;
	}
}