package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="r_issueproject")
public class RIssueProject extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aAssetID;
	private Integer aDClientID;
	private Integer aDOrgID;
	private Boolean active;
	private Integer cProjectID;
	private String created;
	private Integer createdBy;
	private String description;
	private String name;
	private String profileInfo;
	private Integer rIssueProjectID;
	private String statisticsInfo;
	private String systemStatus;
	private String updated;
	private Integer updatedBy;

	public RIssueProject() {
	}

	public RIssueProject(Integer rIssueProjectID) {
		this.rIssueProjectID = rIssueProjectID;
	}

	@Basic
	@Column(name="A_ASSET_ID", columnDefinition="INT")
	public Integer getAAssetID() {
		return aAssetID;
	}

	public void setAAssetID(Integer aAssetID) {
		this.aAssetID = aAssetID;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getADClientID() {
		return aDClientID;
	}

	public void setADClientID(Integer aDClientID) {
		this.aDClientID = aDClientID;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getADOrgID() {
		return aDOrgID;
	}

	public void setADOrgID(Integer aDOrgID) {
		this.aDOrgID = aDOrgID;
	}

	@Basic
	@Column(name="ISACTIVE", nullable=false)
	public Boolean isActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@Basic
	@Column(name="C_PROJECT_ID", columnDefinition="INT")
	public Integer getCProjectID() {
		return cProjectID;
	}

	public void setCProjectID(Integer cProjectID) {
		this.cProjectID = cProjectID;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Basic
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Basic
	@Column(nullable=false, length=60)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Basic
	@Column(length=60)
	public String getProfileInfo() {
		return profileInfo;
	}

	public void setProfileInfo(String profileInfo) {
		this.profileInfo = profileInfo;
	}

	@Id
	@Column(name="R_ISSUEPROJECT_ID", columnDefinition="INT")
	@TableGenerator(name = "PkGen_1205", table = "ad_sequence", pkColumnName = "name", pkColumnValue = "R_IssueProject", valueColumnName = "currentnextsys", allocationSize = 1 )
	@GeneratedValue(strategy = GenerationType.TABLE, generator = "PkGen_1205")
	public Integer getRIssueProjectID() {
		return rIssueProjectID;
	}

	public void setRIssueProjectID(Integer rIssueProjectID) {
		this.rIssueProjectID = rIssueProjectID;
	}

	@Basic
	@Column(length=60)
	public String getStatisticsInfo() {
		return statisticsInfo;
	}

	public void setStatisticsInfo(String statisticsInfo) {
		this.statisticsInfo = statisticsInfo;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getSystemStatus() {
		return systemStatus;
	}

	public void setSystemStatus(String systemStatus) {
		this.systemStatus = systemStatus;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}
}