package org.adempiere.model;

import java.math.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="r_request")
public class RRequest extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer aAssetId;
	private Integer adClientId;
	private Integer adOrgId;
	private Integer adRoleId;
	private Integer adTableId;
	private Integer adUserId;
	private Integer cActivityId;
	private Integer cBpartnerId;
	private Integer cCampaignId;
	private Integer cInvoiceId;
	private Integer cInvoicerequestId;
	private Integer cOrderId;
	private Integer cPaymentId;
	private Integer cProjectId;
	private String closedate;
	private String confidentialtype;
	private String confidentialtypeentry;
	private String created;
	private Integer createdby;
	private String datecompleteplan;
	private String datelastaction;
	private String datelastalert;
	private String datenextaction;
	private String datestartplan;
	private String documentno;
	private String duetype;
	private String endtime;
	private Boolean isactive;
	private Boolean isescalated;
	private Boolean isinvoiced;
	private Boolean isselfservice;
	private String lastresult;
	private Integer mChangerequestId;
	private Integer mFixchangenoticeId;
	private Integer mInoutId;
	private Integer mProductId;
	private Integer mProductspentId;
	private Integer mRmaId;
	private String nextaction;
	private String priority;
	private String priorityuser;
	private Boolean processed;
	private BigDecimal qtyinvoiced;
	private BigDecimal qtyplan;
	private BigDecimal qtyspent;
	private Integer rCategoryId;
	private Integer rGroupId;
	private Integer rMailtextId;
	private Integer rRequestId;
	private Integer rRequestrelatedId;
	private Integer rRequesttypeId;
	private Integer rResolutionId;
	private Integer rStandardresponseId;
	private Integer rStatusId;
	private Integer recordId;
	private BigDecimal requestamt;
	private String result;
	private Integer salesrepId;
	private String startdate;
	private String starttime;
	private String summary;
	private String taskstatus;
	private String updated;
	private Integer updatedby;

	public RRequest() {
	}

	public RRequest(Integer rRequestId) {
		this.rRequestId = rRequestId;
	}

	@Basic
	@Column(name="A_ASSET_ID", columnDefinition="INT")
	public Integer getAAssetId() {
		return aAssetId;
	}

	public void setAAssetId(Integer aAssetId) {
		this.aAssetId = aAssetId;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", columnDefinition="INT", nullable=false)
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name="AD_ORG_ID", columnDefinition="INT", nullable=false)
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Basic
	@Column(name="AD_ROLE_ID", columnDefinition="INT")
	public Integer getAdRoleId() {
		return adRoleId;
	}

	public void setAdRoleId(Integer adRoleId) {
		this.adRoleId = adRoleId;
	}

	@Basic
	@Column(name="AD_TABLE_ID", columnDefinition="INT")
	public Integer getAdTableId() {
		return adTableId;
	}

	public void setAdTableId(Integer adTableId) {
		this.adTableId = adTableId;
	}

	@Basic
	@Column(name="AD_USER_ID", columnDefinition="INT")
	public Integer getAdUserId() {
		return adUserId;
	}

	public void setAdUserId(Integer adUserId) {
		this.adUserId = adUserId;
	}

	@Basic
	@Column(name="C_ACTIVITY_ID", columnDefinition="INT")
	public Integer getCActivityId() {
		return cActivityId;
	}

	public void setCActivityId(Integer cActivityId) {
		this.cActivityId = cActivityId;
	}

	@Basic
	@Column(name="C_BPARTNER_ID", columnDefinition="INT")
	public Integer getCBpartnerId() {
		return cBpartnerId;
	}

	public void setCBpartnerId(Integer cBpartnerId) {
		this.cBpartnerId = cBpartnerId;
	}

	@Basic
	@Column(name="C_CAMPAIGN_ID", columnDefinition="INT")
	public Integer getCCampaignId() {
		return cCampaignId;
	}

	public void setCCampaignId(Integer cCampaignId) {
		this.cCampaignId = cCampaignId;
	}

	@Basic
	@Column(name="C_INVOICE_ID", columnDefinition="INT")
	public Integer getCInvoiceId() {
		return cInvoiceId;
	}

	public void setCInvoiceId(Integer cInvoiceId) {
		this.cInvoiceId = cInvoiceId;
	}

	@Basic
	@Column(name="C_INVOICEREQUEST_ID", columnDefinition="INT")
	public Integer getCInvoicerequestId() {
		return cInvoicerequestId;
	}

	public void setCInvoicerequestId(Integer cInvoicerequestId) {
		this.cInvoicerequestId = cInvoicerequestId;
	}

	@Basic
	@Column(name="C_ORDER_ID", columnDefinition="INT")
	public Integer getCOrderId() {
		return cOrderId;
	}

	public void setCOrderId(Integer cOrderId) {
		this.cOrderId = cOrderId;
	}

	@Basic
	@Column(name="C_PAYMENT_ID", columnDefinition="INT")
	public Integer getCPaymentId() {
		return cPaymentId;
	}

	public void setCPaymentId(Integer cPaymentId) {
		this.cPaymentId = cPaymentId;
	}

	@Basic
	@Column(name="C_PROJECT_ID", columnDefinition="INT")
	public Integer getCProjectId() {
		return cProjectId;
	}

	public void setCProjectId(Integer cProjectId) {
		this.cProjectId = cProjectId;
	}

	@Basic
	public String getClosedate() {
		return closedate;
	}

	public void setClosedate(String closedate) {
		this.closedate = closedate;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getConfidentialtype() {
		return confidentialtype;
	}

	public void setConfidentialtype(String confidentialtype) {
		this.confidentialtype = confidentialtype;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getConfidentialtypeentry() {
		return confidentialtypeentry;
	}

	public void setConfidentialtypeentry(String confidentialtypeentry) {
		this.confidentialtypeentry = confidentialtypeentry;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getCreatedby() {
		return createdby;
	}

	public void setCreatedby(Integer createdby) {
		this.createdby = createdby;
	}

	@Basic
	public String getDatecompleteplan() {
		return datecompleteplan;
	}

	public void setDatecompleteplan(String datecompleteplan) {
		this.datecompleteplan = datecompleteplan;
	}

	@Basic
	public String getDatelastaction() {
		return datelastaction;
	}

	public void setDatelastaction(String datelastaction) {
		this.datelastaction = datelastaction;
	}

	@Basic
	public String getDatelastalert() {
		return datelastalert;
	}

	public void setDatelastalert(String datelastalert) {
		this.datelastalert = datelastalert;
	}

	@Basic
	public String getDatenextaction() {
		return datenextaction;
	}

	public void setDatenextaction(String datenextaction) {
		this.datenextaction = datenextaction;
	}

	@Basic
	public String getDatestartplan() {
		return datestartplan;
	}

	public void setDatestartplan(String datestartplan) {
		this.datestartplan = datestartplan;
	}

	@Basic
	@Column(nullable=false, length=30)
	public String getDocumentno() {
		return documentno;
	}

	public void setDocumentno(String documentno) {
		this.documentno = documentno;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getDuetype() {
		return duetype;
	}

	public void setDuetype(String duetype) {
		this.duetype = duetype;
	}

	@Basic
	public String getEndtime() {
		return endtime;
	}

	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsactive() {
		return isactive;
	}

	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsescalated() {
		return isescalated;
	}

	public void setIsescalated(Boolean isescalated) {
		this.isescalated = isescalated;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsinvoiced() {
		return isinvoiced;
	}

	public void setIsinvoiced(Boolean isinvoiced) {
		this.isinvoiced = isinvoiced;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isIsselfservice() {
		return isselfservice;
	}

	public void setIsselfservice(Boolean isselfservice) {
		this.isselfservice = isselfservice;
	}

	@Basic
	@Column(length=2000)
	public String getLastresult() {
		return lastresult;
	}

	public void setLastresult(String lastresult) {
		this.lastresult = lastresult;
	}

	@Basic
	@Column(name="M_CHANGEREQUEST_ID", columnDefinition="INT")
	public Integer getMChangerequestId() {
		return mChangerequestId;
	}

	public void setMChangerequestId(Integer mChangerequestId) {
		this.mChangerequestId = mChangerequestId;
	}

	@Basic
	@Column(name="M_FIXCHANGENOTICE_ID", columnDefinition="INT")
	public Integer getMFixchangenoticeId() {
		return mFixchangenoticeId;
	}

	public void setMFixchangenoticeId(Integer mFixchangenoticeId) {
		this.mFixchangenoticeId = mFixchangenoticeId;
	}

	@Basic
	@Column(name="M_INOUT_ID", columnDefinition="INT")
	public Integer getMInoutId() {
		return mInoutId;
	}

	public void setMInoutId(Integer mInoutId) {
		this.mInoutId = mInoutId;
	}

	@Basic
	@Column(name="M_PRODUCT_ID", columnDefinition="INT")
	public Integer getMProductId() {
		return mProductId;
	}

	public void setMProductId(Integer mProductId) {
		this.mProductId = mProductId;
	}

	@Basic
	@Column(name="M_PRODUCTSPENT_ID", columnDefinition="INT")
	public Integer getMProductspentId() {
		return mProductspentId;
	}

	public void setMProductspentId(Integer mProductspentId) {
		this.mProductspentId = mProductspentId;
	}

	@Basic
	@Column(name="M_RMA_ID", columnDefinition="INT")
	public Integer getMRmaId() {
		return mRmaId;
	}

	public void setMRmaId(Integer mRmaId) {
		this.mRmaId = mRmaId;
	}

	@Basic
	@Column(length=1)
	public String getNextaction() {
		return nextaction;
	}

	public void setNextaction(String nextaction) {
		this.nextaction = nextaction;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getPriority() {
		return priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	@Basic
	@Column(length=1)
	public String getPriorityuser() {
		return priorityuser;
	}

	public void setPriorityuser(String priorityuser) {
		this.priorityuser = priorityuser;
	}

	@Basic
	@Column(nullable=false)
	public Boolean isProcessed() {
		return processed;
	}

	public void setProcessed(Boolean processed) {
		this.processed = processed;
	}

	@Basic
	public BigDecimal getQtyinvoiced() {
		return qtyinvoiced;
	}

	public void setQtyinvoiced(BigDecimal qtyinvoiced) {
		this.qtyinvoiced = qtyinvoiced;
	}

	@Basic
	public BigDecimal getQtyplan() {
		return qtyplan;
	}

	public void setQtyplan(BigDecimal qtyplan) {
		this.qtyplan = qtyplan;
	}

	@Basic
	public BigDecimal getQtyspent() {
		return qtyspent;
	}

	public void setQtyspent(BigDecimal qtyspent) {
		this.qtyspent = qtyspent;
	}

	@Basic
	@Column(name="R_CATEGORY_ID", columnDefinition="INT")
	public Integer getRCategoryId() {
		return rCategoryId;
	}

	public void setRCategoryId(Integer rCategoryId) {
		this.rCategoryId = rCategoryId;
	}

	@Basic
	@Column(name="R_GROUP_ID", columnDefinition="INT")
	public Integer getRGroupId() {
		return rGroupId;
	}

	public void setRGroupId(Integer rGroupId) {
		this.rGroupId = rGroupId;
	}

	@Basic
	@Column(name="R_MAILTEXT_ID", columnDefinition="INT")
	public Integer getRMailtextId() {
		return rMailtextId;
	}

	public void setRMailtextId(Integer rMailtextId) {
		this.rMailtextId = rMailtextId;
	}

	@Id
	@Column(name="R_REQUEST_ID", columnDefinition="INT")
	public Integer getRRequestId() {
		return rRequestId;
	}

	public void setRRequestId(Integer rRequestId) {
		this.rRequestId = rRequestId;
	}

	@Basic
	@Column(name="R_REQUESTRELATED_ID", columnDefinition="INT")
	public Integer getRRequestrelatedId() {
		return rRequestrelatedId;
	}

	public void setRRequestrelatedId(Integer rRequestrelatedId) {
		this.rRequestrelatedId = rRequestrelatedId;
	}

	@Basic
	@Column(name="R_REQUESTTYPE_ID", columnDefinition="INT", nullable=false)
	public Integer getRRequesttypeId() {
		return rRequesttypeId;
	}

	public void setRRequesttypeId(Integer rRequesttypeId) {
		this.rRequesttypeId = rRequesttypeId;
	}

	@Basic
	@Column(name="R_RESOLUTION_ID", columnDefinition="INT")
	public Integer getRResolutionId() {
		return rResolutionId;
	}

	public void setRResolutionId(Integer rResolutionId) {
		this.rResolutionId = rResolutionId;
	}

	@Basic
	@Column(name="R_STANDARDRESPONSE_ID", columnDefinition="INT")
	public Integer getRStandardresponseId() {
		return rStandardresponseId;
	}

	public void setRStandardresponseId(Integer rStandardresponseId) {
		this.rStandardresponseId = rStandardresponseId;
	}

	@Basic
	@Column(name="R_STATUS_ID", columnDefinition="INT")
	public Integer getRStatusId() {
		return rStatusId;
	}

	public void setRStatusId(Integer rStatusId) {
		this.rStatusId = rStatusId;
	}

	@Basic
	@Column(name="RECORD_ID", columnDefinition="INT")
	public Integer getRecordId() {
		return recordId;
	}

	public void setRecordId(Integer recordId) {
		this.recordId = recordId;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getRequestamt() {
		return requestamt;
	}

	public void setRequestamt(BigDecimal requestamt) {
		this.requestamt = requestamt;
	}

	@Basic
	@Column(length=2000)
	public String getResult() {
		return result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Basic
	@Column(name="SALESREP_ID", columnDefinition="INT", nullable=false)
	public Integer getSalesrepId() {
		return salesrepId;
	}

	public void setSalesrepId(Integer salesrepId) {
		this.salesrepId = salesrepId;
	}

	@Basic
	public String getStartdate() {
		return startdate;
	}

	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}

	@Basic
	public String getStarttime() {
		return starttime;
	}

	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	@Basic
	@Column(nullable=false, length=2000)
	public String getSummary() {
		return summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Basic
	@Column(length=1)
	public String getTaskstatus() {
		return taskstatus;
	}

	public void setTaskstatus(String taskstatus) {
		this.taskstatus = taskstatus;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(columnDefinition="INT", nullable=false)
	public Integer getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}
}