package org.adempiere.model;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="t_selection")
@IdClass(org.adempiere.model.TSelectionPK.class)
public class TSelection extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer adPinstanceId;
	private Integer tSelectionId;

	public TSelection() {
	}

	public TSelection(Integer adPinstanceId, Integer tSelectionId) {
		this.adPinstanceId = adPinstanceId;
		this.tSelectionId = tSelectionId;
	}

	@Id
	@Column(name="AD_PINSTANCE_ID")
	public Integer getAdPinstanceId() {
		return adPinstanceId;
	}

	public void setAdPinstanceId(Integer adPinstanceId) {
		this.adPinstanceId = adPinstanceId;
	}

	@Id
	@Column(name="T_SELECTION_ID")
	public Integer getTSelectionId() {
		return tSelectionId;
	}

	public void setTSelectionId(Integer tSelectionId) {
		this.tSelectionId = tSelectionId;
	}
}