package org.adempiere.model;

import java.math.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.adempiere.AdempiereCustomizer
 */
@Entity
@Table(name="u_web_properties")
public class UWebProperties extends org.adempiere.common.ADEntityBase {
	private static final long serialVersionUID = 1L;
	private Integer adClientId;
	private Integer adOrgId;
	private String created;
	private BigDecimal createdby;
	private String isactive;
	private String uKey;
	private String uValue;
	private Integer uWebPropertiesId;
	private String updated;
	private BigDecimal updatedby;

	public UWebProperties() {
	}

	public UWebProperties(Integer uWebPropertiesId) {
		this.uWebPropertiesId = uWebPropertiesId;
	}

	@Basic
	@Column(name="AD_CLIENT_ID", nullable=false)
	public Integer getAdClientId() {
		return adClientId;
	}

	public void setAdClientId(Integer adClientId) {
		this.adClientId = adClientId;
	}

	@Basic
	@Column(name="AD_ORG_ID", nullable=false)
	public Integer getAdOrgId() {
		return adOrgId;
	}

	public void setAdOrgId(Integer adOrgId) {
		this.adOrgId = adOrgId;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getCreated() {
		return created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getCreatedby() {
		return createdby;
	}

	public void setCreatedby(BigDecimal createdby) {
		this.createdby = createdby;
	}

	@Basic
	@Column(nullable=false, length=1)
	public String getIsactive() {
		return isactive;
	}

	public void setIsactive(String isactive) {
		this.isactive = isactive;
	}

	@Basic
	@Column(name="U_KEY", nullable=false, length=240)
	public String getUKey() {
		return uKey;
	}

	public void setUKey(String uKey) {
		this.uKey = uKey;
	}

	@Basic
	@Column(name="U_VALUE", nullable=false, length=240)
	public String getUValue() {
		return uValue;
	}

	public void setUValue(String uValue) {
		this.uValue = uValue;
	}

	@Id
	@Column(name="U_WEB_PROPERTIES_ID")
	public Integer getUWebPropertiesId() {
		return uWebPropertiesId;
	}

	public void setUWebPropertiesId(Integer uWebPropertiesId) {
		this.uWebPropertiesId = uWebPropertiesId;
	}

	@Basic
	@Column(columnDefinition="TIMESTAMP", nullable=false)
	public String getUpdated() {
		return updated;
	}

	public void setUpdated(String updated) {
		this.updated = updated;
	}

	@Basic
	@Column(nullable=false)
	public BigDecimal getUpdatedby() {
		return updatedby;
	}

	public void setUpdatedby(BigDecimal updatedby) {
		this.updatedby = updatedby;
	}
}